## pb371 Using the Open Weather Map API, find the location of ahmedabad

In [1]:
import requests
api_key = "3beddd7f21592afe5787c62211bca984"
response = requests.get("http://api.openweathermap.org/geo/1.0/direct?q=Ahmedabad&limit=5&appid="+api_key)
print(response.json())

[{'name': 'Ahmedabad', 'local_names': {'pa': 'ਅਹਿਮਦਾਬਾਦ', 'ml': 'അഹമ്മദാബാദ്', 'bn': 'আহমেদাবাদ', 'ja': 'アフマダーバード', 'or': 'ଅହମଦାବାଦ', 'uk': 'Ахмедабад', 'hi': 'अहमदाबाद', 'eo': 'Ahmadabado', 'en': 'Ahmedabad', 'ne': 'अहमदाबाद', 'mr': 'अहमदाबाद', 'he': 'אחמדאבאד', 'kn': 'ಅಹ್ಮದಾಬಾದ್', 'zh': '艾哈迈达巴德', 'ur': 'احمد آباد', 'gu': 'અમદાવાદ', 'ru': 'Ахмадабад', 'ascii': 'Ahmedabad', 'cs': 'Ahmadábád', 'ta': 'அகமதாபாத்', 'tt': 'Әхмәтабад', 'pl': 'Ahmadabad', 'feature_name': 'Ahmedabad', 'ar': 'أحمد آباد', 'de': 'Ahmedabad', 'oc': 'Ahmadabad', 'te': 'అహ్మదాబాద్'}, 'lat': 23.0215374, 'lon': 72.5800568, 'country': 'IN', 'state': 'Gujarat'}, {'name': 'Ahmedabad', 'local_names': {'en': 'Ahmedabad'}, 'lat': 32.5022729, 'lon': 72.8536319, 'country': 'PK', 'state': 'Punjab'}, {'name': 'Ahmedabad', 'local_names': {'en': 'Ahmedabad'}, 'lat': 24.7312039, 'lon': 67.6891818, 'country': 'PK', 'state': 'Sindh'}, {'name': 'Ahmedabad', 'lat': 32.9649355, 'lon': 74.2725539, 'country': 'PK', 'state': 'Azad Kashmir'}, {'name': 'Ahmedabad', 'local_names': {'en': 'Ahmedabad'}, 'lat': 31.4963792, 'lon': 72.0759963, 'country': 'PK', 'state': 'Punjab'}]

In [2]:
import json
data = response.json()
print(json.dumps(data, indent=5))

[
     {
          "name": "Ahmedabad",
          "local_names": {
               "pa": "\u0a05\u0a39\u0a3f\u0a2e\u0a26\u0a3e\u0a2c\u0a3e\u0a26",
               "ml": "\u0d05\u0d39\u0d2e\u0d4d\u0d2e\u0d26\u0d3e\u0d2c\u0d3e\u0d26\u0d4d",
               "bn": "\u0986\u09b9\u09ae\u09c7\u09a6\u09be\u09ac\u09be\u09a6",
               "ja": "\u30a2\u30d5\u30de\u30c0\u30fc\u30d0\u30fc\u30c9",
               "or": "\u0b05\u0b39\u0b2e\u0b26\u0b3e\u0b2c\u0b3e\u0b26",
               "uk": "\u0410\u0445\u043c\u0435\u0434\u0430\u0431\u0430\u0434",
               "hi": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "eo": "Ahmadabado",
               "en": "Ahmedabad",
               "ne": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "mr": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "he": "\u05d0\u05d7\u05de\u05d3\u05d0\u05d1\u05d0\u05d3",
               "kn": "\u0c85\u0cb9\u0ccd\u0cae\u0ca6\u0cbe\u0cac\u0cbe\u0ca6\u0ccd",
               "zh": "\u827e\u54c8\u8fc8\u8fbe\u5df4\u5fb7",
               "ur": "\u0627\u062d\u0645\u062f \u0622\u0628\u0627\u062f",
               "gu": "\u0a85\u0aae\u0aa6\u0abe\u0ab5\u0abe\u0aa6",
               "ru": "\u0410\u0445\u043c\u0430\u0434\u0430\u0431\u0430\u0434",
               "ascii": "Ahmedabad",
               "cs": "Ahmad\u00e1b\u00e1d",
               "ta": "\u0b85\u0b95\u0bae\u0ba4\u0bbe\u0baa\u0bbe\u0ba4\u0bcd",
               "tt": "\u04d8\u0445\u043c\u04d9\u0442\u0430\u0431\u0430\u0434",
               "pl": "Ahmadabad",
               "feature_name": "Ahmedabad",
               "ar": "\u0623\u062d\u0645\u062f \u0622\u0628\u0627\u062f",
               "de": "Ahmedabad",
               "oc": "Ahmadabad",
               "te": "\u0c05\u0c39\u0c4d\u0c2e\u0c26\u0c3e\u0c2c\u0c3e\u0c26\u0c4d"
          },
          "lat": 23.0215374,
          "lon": 72.5800568,
          "country": "IN",
          "state": "Gujarat"
     },
     {
          "name": "Ahmedabad",
          "local_names": {
               "en": "Ahmedabad"
          },
          "lat": 32.5022729,
          "lon": 72.8536319,
          "country": "PK",
          "state": "Punjab"
     },
     {
          "name": "Ahmedabad",
          "local_names": {
               "en": "Ahmedabad"
          },
          "lat": 24.7312039,
          "lon": 67.6891818,
          "country": "PK",
          "state": "Sindh"
     },
     {
          "name": "Ahmedabad",
          "lat": 32.9649355,
          "lon": 74.2725539,
          "country": "PK",
          "state": "Azad Kashmir"
     },
     {
          "name": "Ahmedabad",
          "local_names": {
               "en": "Ahmedabad"
          },
          "lat": 31.4963792,
          "lon": 72.0759963,
          "country": "PK",
          "state": "Punjab"
     }
]

In [3]:
lat = data[0]['lat']
lon = data[0]['lon']
print(lat, lon)

23.0215374 72.5800568

## Pb369 Using Open Weather Map API, generate current air pollution data forAhmedabad and extract detail of aqi.

In [4]:
response = f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={api_key}"
response = requests.get(response)
data = response.json()
print(data)

{'coord': {'lon': 72.5801, 'lat': 23.0215}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'base': 'stations', 'main': {'temp': 312.37, 'feels_like': 314.02, 'temp_min': 312.37, 'temp_max': 312.37, 'pressure': 1005, 'humidity': 28, 'sea_level': 1005, 'grnd_level': 1000}, 'visibility': 10000, 'wind': {'speed': 4.61, 'deg': 244, 'gust': 4.84}, 'clouds': {'all': 1}, 'dt': 1781598033, 'sys': {'country': 'IN', 'sunrise': 1781569445, 'sunset': 1781618196}, 'timezone': 19800, 'id': 1279233, 'name': 'Ahmedabad', 'cod': 200}

In [5]:
print(json.dumps(data, indent=5))

{
     "coord": {
          "lon": 72.5801,
          "lat": 23.0215
     },
     "weather": [
          {
               "id": 800,
               "main": "Clear",
               "description": "clear sky",
               "icon": "01d"
          }
     ],
     "base": "stations",
     "main": {
          "temp": 312.37,
          "feels_like": 314.02,
          "temp_min": 312.37,
          "temp_max": 312.37,
          "pressure": 1005,
          "humidity": 28,
          "sea_level": 1005,
          "grnd_level": 1000
     },
     "visibility": 10000,
     "wind": {
          "speed": 4.61,
          "deg": 244,
          "gust": 4.84
     },
     "clouds": {
          "all": 1
     },
     "dt": 1781598033,
     "sys": {
          "country": "IN",
          "sunrise": 1781569445,
          "sunset": 1781618196
     },
     "timezone": 19800,
     "id": 1279233,
     "name": "Ahmedabad",
     "cod": 200
}

## pb371 Write a Python program using beautiful soup to scrape all the news headlines in the div class “top news” from
https://indianexpress.com/

In [6]:
import bs4
response = requests.get("https://indianexpress.com/")
print(response)

<Response [200]>

In [7]:
data = response.text
print(data)

<!DOCTYPE html>
<html lang="en" xmlns:og="https://ogp.me/ns#">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=1300">

    <title>Latest News Today, Breaking News, India News, Top Headlines | The Indian Express</title><meta property="fb:pages" content="163648403825" /><meta property="fb:pages" content="168619349359" /><meta property="fb:pages" content="185763818464532" /><meta property="fb:pages" content="1494497934210205" /><meta property="fb:pages" content="1774784956154724" /><meta property="fb:pages" content="1567211863297748" /><meta property="fb:pages" content="291465928041678" /><meta property="fb:pages" content="339520043138547" /><meta property="fb:pages" content="376556412852346" /><meta property="fb:pages" content="215732349153100" /><meta name="description" content="Get the latest news today, breaking news, and top news headlines updates from India and around the world. Stay updated on politics, business, sports, entertainment, and more with The Indian Express." /><meta name="keywords" content="News, Latest News, Breaking News, Live News, India News, News Online, News Headlines, News Today, English News, Top Stories" /><meta property="og:type" content="website" /><meta property="og:url" content="https://indianexpress.com/" /><meta property="og:site_name" content="The Indian Express" /><meta property="og:locale" content="en_US" /><meta property="og:title" content="Latest News Today, Breaking News, India News, Top Headlines| The Indian Express" /><meta property="og:description" content="Get the latest news today, breaking news, and top news headlines updates from India and around the world. Stay updated on politics, business, sports, entertainment, and more with The Indian Express." /><meta property="og:image" content="https://indianexpress.com/wp-content/themes/indianexpress/images/IE-OGimage.jpg" /><meta property="og:image:type" content="image/jpeg" /><meta property="og:image:width" content="1200" /><meta property="og:image:height" content="667" /><meta name="twitter:card" content="summary_large_image"><meta name="twitter:site" content="The Indian Express"><meta name="twitter:creator" content="@indianexpress" /><meta name="twitter:url" content="https://indianexpress.com/"><meta name="twitter:title" content="Latest News Today, Breaking News, India News, Top Headlines| The Indian Express"><meta name="twitter:description" content="Get the latest news today, breaking news, and top news headlines updates from India and around the world. Stay updated on politics, business, sports, entertainment, and more with The Indian Express."><meta property="twitter:image" content="https://indianexpress.com/wp-content/themes/indianexpress/images/IE-OGimage.jpg" /><meta property="twitter:image:type" content="image/jpeg" /><meta property="twitter:image:width" content="1200" /><meta property="twitter:image:height" content="667" /><meta itemprop="inLanguage" content="en" /><meta itemprop="name" content="Latest News Today, Breaking News, India News, Top Headlines| The Indian Express"><meta itemprop="mainEntityOfPage" content="https://indianexpress.com/" /><meta itemprop="url" content="https://indianexpress.com/" /><meta itemprop="headline" content="Latest News Today, Breaking News, India News, Top Headlines| The Indian Express" /><meta itemprop="description" content="Get the latest news today, breaking news, and top news headlines updates from India and around the world. Stay updated on politics, business, sports, entertainment, and more with The Indian Express." /><meta itemprop="keywords" content="News, Latest News, Breaking News, Live News, India News, News Online, News Headlines, News Today, English News, Top Stories"><script type="application/ld+json">{"@context":"https:\/\/schema.org","@type":"WebPage","name":"Latest News Today, Breaking News, India News, Top Headlines| The Indian Express","description":"Get the latest news today, breaking news, and top news headlines updates from India and around the world. Stay updated on politics, business, sports, entertainment, and more with The Indian Express.","keywords":"News, Latest News, Breaking News, Live News, India News, News Online, News Headlines, News Today, English News, Top Stories","url":"https:\/\/indianexpress.com\/","mainContentOFPage":"News","inLanguage":"en","lastReviewed":"2026-06-16"}</script><script type="application/ld+json">{
			"@context":"https://schema.org/",
			"@type":"ViewAction",
			"target":{
				"type":"EntryPoint",
				"urlTemplate":"https://indexpress.page.link/shareDL"
			}
		}</script><meta name="ahrefs-site-verification" content="00120a3a212c33eda15559fea6d0731769fd82f538180bd0a2dbe12991312ab4"><meta name="robots" content="NOODP" /><meta name="majestic-site-verification" content="MJ12_ad7db024-a46c-482a-bb2f-e1ae09432a65">
	<script>window.criteo_pubtag = window.criteo_pubtag || {};window.criteo_pubtag.disableSync = true;</script>
	<meta name='robots' content='max-image-preview:large' />
	<style>img:is([sizes="auto" i], [sizes^="auto," i]) { contain-intrinsic-size: 3000px 1500px }</style>
			<script>
			let iersisAbtesting='yes';
			let iersCampName='v2-campaign-sub-1-4-20260514';
			let iersACohert=100;
			let iersShowAwsRegisteredUser='yes';
			let iersLoyaltyType='{"enable_aws_loyalty":"sessionLoyalty","casual":"1","repeat":"1","engaged":"1","loyal":"1","brandlover":"1"}';
			let iersCampNameRegistered='v2-campaign-reg-1-4-20260511';
			let iersACohertRegistered=50;
			let iersRemainingLoyaltyType='{"enable_aws_loyalty":"sessionLoyalty","casual":"1","repeat":"1","engaged":"1","loyal":"1","brandlover":"1"}';
			let iersCampNameRemainingRegistered='v2-campaign-reg-1-4-20260511';
			let iersACohertRemainingRegistered='50';
			let iersVersionSubscriber='sub-1.4';
			let iersVersion1Registered='reg-1.4';
			let iersVersion2Registered='reg-1.4';
			let iersPageLoadEvent ='yes';
			let iersShowAwsAnonymousUser='yes';
			let iersCampNameAnonymous='v2-campaign-ano-1-0-20260515';
			let iersACohertAnonymous='5';
			let iersVersionAnonymous='ano-1.0';
			let iersUserType="anonymous_user",iersVersion="",currentURLIers=window.location.href;var urlIers=new URL(currentURLIers),urlKeyIers=urlIers.searchParams.get("taboolatype");let iersRegisteredUsersLoyaltyPass=!1,iersNonLoyaltyRegisteredUser=!1,iersRegisterUser2_0=!1,iersABtestCase=!1,iersSavedSegmentName=iersGetWithExpiry("iers_segment_name"),iersSegmentName="",iersUserPlanDetails=[],iersUserDetails=!1,iersUserState="guest";null!==iersSavedSegmentName&&(iersSegmentName=iersSavedSegmentName.name);let iersSavedUserTopSections=iersGetWithExpiry("iers_user_top_sections"),iersUserTopSections=[];null!==iersSavedUserTopSections&&(iersUserTopSections=iersSavedUserTopSections.name);let iersLoggedinUserDetails=null,iers_allocation_done=!1,iers_isAwsUser=!1,iers_resolveAllocation=[];function iersIsAwsUsersList(){return new Promise(e=>{if(iers_allocation_done)return e(iers_isAwsUser);iers_resolveAllocation.push(e)})}function iersGlobalGetCookie(e){let r=e+"=",s=decodeURIComponent(document.cookie).split(";");for(let e=0;e<s.length;e++){let i=s[e];for(;" "==i.charAt(0);)i=i.substring(1);if(0==i.indexOf(r))return i.substring(r.length,i.length)}return""}function iersGlobalUndefinedCheck(e){let r=!1;return void 0!==e&&""!==e&&null!==e&&(r=!0),r}function iersCheckIfSubscriberAllowed(e){let r=!1;return!0===[10346934,209186,15268894,209185,203493,208633,208634,208635,208636,208637,208638,208639,208640,208641,208642,208643,208644,208645,208646,208648,208649,208650,13232261,14839323,3432583,10521544,8105709,785651,6805839,4726075,4382867,10095307,35,3640408,49,6591,19716,6564,8481,9415574,208807,13232532].includes(e)&&(r=!0),r}function iersCheckIfSubscriberEmailAllowed(e){return"string"==typeof e&&""!==e&&(e.endsWith("@indianexpress.com")||e.endsWith("@expressindia.com"))}function iersGetAlphaUsers(e,r){return(!0===iersCheckIfSubscriberAllowed(e)||!0===iersCheckIfSubscriberEmailAllowed(r))&&(iersUserType="alpha_user",!0)}async function iersIsAwsSubscriber(e){if(null!==iersLoggedinUserDetails){let e=iersHardcodedEmails(iersLoggedinUserDetails.user_email);if(!1!==e)return e}let r="subscriber_personalization",s=50;"undefined"!=typeof iersCampName&&iersCampName&&"undefined"!=typeof iersACohert&&iersACohert&&(r=iersCampName,s=iersACohert);let i=await iersassignVariantFromSsoid(e,s);return iersUserType="variant_personalize","B"===i&&(iersUserType="control_taboola"),null!=urlKeyIers&&""!==urlKeyIers&&(iersUserType="variant_personalize",i="A","control_taboola"===urlKeyIers&&(iersUserType="control_taboola",i="B")),i}function iersstr2ab(e){const r=new ArrayBuffer(e.length),s=new Uint8Array(r);for(let r=0;r<e.length;r++)s[r]=e.charCodeAt(r);return r}function iersab2hex(e){const r=[],s=new Uint8Array(e);for(let e=0;e<s.length;e++){const i=s[e].toString(16).padStart(2,"0");r.push(i)}return r.join("")}async function ierssha256Hex(e){return iersab2hex(await crypto.subtle.digest("SHA-256",iersstr2ab(e)))}async function iersassignVariantFromSsoid(e=null,r=10){if(r<0||r>100)throw new Error("percentageA must be between 0 and 100");let s=e?String(e).trim():"";return iersHexMod(await ierssha256Hex(s),100)<r?"A":"B"}function iersHexMod(e,r){let s=0;for(let i=0;i<e.length;i++)s=(16*s+parseInt(e[i],16))%r;return s}function iersGetVersion(){let e=iersGlobalGetCookie("ev_user_state"),r="";return"subscriber"===e?r=iersVersionSubscriber:"registered"===e?(r=iersVersion1Registered,!0===iersRegisterUser2_0&&(r=iersVersion2Registered)):"guest"===e&&(r=iersVersionAnonymous),iersVersion=r,r}function iersGetLoyaltyInfo(){let e=iersGlobalGetCookie("userLoyaltyBand"),r=!1;if(!0===iersGlobalUndefinedCheck(e))try{let s=JSON.parse(e);!0===iersGlobalUndefinedCheck(s)&&(s=JSON.parse(s),s&&"object"==typeof s&&(r={pvLoyalty:s.plb,sessionLoyalty:s.slb}))}catch(e){console.error("Unable to parse userLoyaltyBand",e)}return r}async function iersIsAwsRegisteredUser(e,r,s){if(null!==iersLoggedinUserDetails){let e=iersHardcodedEmails(iersLoggedinUserDetails.user_email);if(!1!==e)return e}let i=await iersassignVariantFromSsoid(e,s);return iersUserType="variant_personalize","B"===i&&(iersUserType="control_taboola"),null!=urlKeyIers&&""!==urlKeyIers&&(iersUserType="variant_personalize",i="A","control_taboola"===urlKeyIers&&(iersUserType="control_taboola",i="B")),i}function iersSetWithExpiry(e,r,s){const i={value:r,expiry:(new Date).getTime()+s};localStorage.setItem(e,JSON.stringify(i))}function iersGetWithExpiry(e){const r=localStorage.getItem(e);if(!r)return null;const s=JSON.parse(r);return(new Date).getTime()>s.expiry?(localStorage.removeItem(e),null):s.value}function iersHardcodedEmails(e){return"string"==typeof e&&""!==e&&void 0!==e&&("developregister@mailinator.com"===(e=e.toLowerCase())||"subscribeharshitpreprod@mailinator.com"===e?(iersUserType="variant_personalize","A"):("developregister1@mailinator.com"===e||"newsubscribepreprod@mailinator.com"===e)&&(iersUserType="control_taboola","B"))}window.addEventListener("iers_allocation_done",e=>{iers_allocation_done=!0,iers_resolveAllocation.length>0&&iers_resolveAllocation.forEach(function(e){e(iers_isAwsUser)})},{once:!0});
		</script>
		<link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin><link rel="preconnect" href="https://www.googletagservices.com/" /><link rel="preconnect" href="https://ads.pubmatic.com/"><link rel="preconnect" href="https://tpc.googlesyndication.com/"><link rel="preconnect" href="https://securepubads.g.doubleclick.net/"><link rel="preconnect" href="https://www.google.com/"><link rel="preconnect" href="https://googleads.g.doubleclick.net/"><link rel="preconnect" href="https://ads.pubmatic.com/"><link rel="preconnect" href="https://www.google-analytics.com/"><link rel="preconnect" href="https://apis.google.com/"><link rel="preconnect" href="https://www.googletagmanager.com/"><link rel="preconnect" href="https://cdn.moengage.com/"><link rel="preconnect" href="https://sb.scorecardresearch.com/"><link rel="preconnect" href="https://ua.indianexpress.com/"><link rel="dns-prefetch" href="https://fonts.gstatic.com/" crossorigin><link rel="dns-prefetch" href="https://www.googletagservices.com/" /><link rel="dns-prefetch" href="https://ads.pubmatic.com/"><link rel="dns-prefetch" href="https://tpc.googlesyndication.com/"><link rel="dns-prefetch" href="https://securepubads.g.doubleclick.net/"><link rel="dns-prefetch" href="https://www.google.com/"><link rel="dns-prefetch" href="https://googleads.g.doubleclick.net/"><link rel="dns-prefetch" href="https://ads.pubmatic.com/"><link rel="dns-prefetch" href="https://www.google-analytics.com/"><link rel="dns-prefetch" href="https://apis.google.com/"><link rel="dns-prefetch" href="https://www.googletagmanager.com/"><link rel="dns-prefetch" href="https://cdn.moengage.com/"><link rel="dns-prefetch" href="https://sb.scorecardresearch.com/"><link rel="dns-prefetch" href="https://ua.indianexpress.com/"><link rel="preconnect" href="https://rtbcdn.andbeyond.media"><link rel="dns-prefetch" href="https://rtbcdn.andbeyond.media"><link rel="preconnect" href="https://rtbpass-us.andbeyond.media"><link rel="dns-prefetch" href="https://rtbpass-us.andbeyond.media"><link rel="preconnect" href="https://cdn.taboola.com" crossorigin><link rel="dns-prefetch" href="//cdn.taboola.com"><link rel="preconnect" href="https://static.chartbeat.com/"><link rel="dns-prefetch" href="https://static.chartbeat.com/"><link rel="preload" href="https://fonts.gstatic.com/s/ptserif/v18/EJRVQgYoZZY2vCFuvAFWzr8.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="https://fonts.gstatic.com/s/roboto/v47/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmUiAo.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="https://fonts.gstatic.com/s/ptserif/v18/EJRSQgYoZZY2vCFuvAnt66qSVys.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="https://fonts.gstatic.com/s/roboto/v47/KFO7CnqEu92Fr1ME7kSn66aGLdTylUAMa3yUBHMdazQ.woff2" as="font" type="font/woff2" crossorigin><style>@font-face{font-family:'PT Serif';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/ptserif/v18/EJRVQgYoZZY2vCFuvAFWzr8.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:Roboto;font-style:normal;font-weight:700;font-stretch:100%;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v47/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmUiAo.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:'PT Serif';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/ptserif/v18/EJRSQgYoZZY2vCFuvAnt66qSVys.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:Roboto;font-style:normal;font-weight:400;font-stretch:100%;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v47/KFO7CnqEu92Fr1ME7kSn66aGLdTylUAMa3yUBHMdazQ.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}</style><!-- Jetpack Site Verification Tags -->
<meta name="google-site-verification" content="GksxYjGFLX8yIx8g5v-Jg5XueVMsv23jAO2UE8hpetM" />
<meta name="msvalidate.01" content="CCA9DA5B985004F4462DA743E776C636" />
<style type="text/css" data-id="inline-css-060620261621">@charset 'UTF-8';

In [8]:
soup = bs4.BeautifulSoup(data, "html.parser")
print(soup.prettify())

<!DOCTYPE html>
<html lang="en" xmlns:og="https://ogp.me/ns#">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=1300" name="viewport"/>
  <title>
   Latest News Today, Breaking News, India News, Top Headlines | The Indian Express
  </title>
  <meta content="163648403825" property="fb:pages">
   <meta content="168619349359" property="fb:pages">
    <meta content="185763818464532" property="fb:pages"/>
    <meta content="1494497934210205" property="fb:pages"/>
    <meta content="1774784956154724" property="fb:pages"/>
    <meta content="1567211863297748" property="fb:pages"/>
    <meta content="291465928041678" property="fb:pages"/>
    <meta content="339520043138547" property="fb:pages"/>
    <meta content="376556412852346" property="fb:pages"/>
    <meta content="215732349153100" property="fb:pages"/>
    <meta content="Get the latest news today, breaking news, and top news headlines updates from India and around the world. Stay updated on politics, business, sports, entertainment, and more with The Indian Express." name="description"/>
    <meta content="News, Latest News, Breaking News, Live News, India News, News Online, News Headlines, News Today, English News, Top Stories" name="keywords"/>
    <meta content="website" property="og:type"/>
    <meta content="https://indianexpress.com/" property="og:url"/>
    <meta content="The Indian Express" property="og:site_name"/>
    <meta content="en_US" property="og:locale"/>
    <meta content="Latest News Today, Breaking News, India News, Top Headlines| The Indian Express" property="og:title"/>
    <meta content="Get the latest news today, breaking news, and top news headlines updates from India and around the world. Stay updated on politics, business, sports, entertainment, and more with The Indian Express." property="og:description"/>
    <meta content="https://indianexpress.com/wp-content/themes/indianexpress/images/IE-OGimage.jpg" property="og:image"/>
    <meta content="image/jpeg" property="og:image:type"/>
    <meta content="1200" property="og:image:width"/>
    <meta content="667" property="og:image:height"/>
    <meta content="summary_large_image" name="twitter:card"/>
    <meta content="The Indian Express" name="twitter:site"/>
    <meta content="@indianexpress" name="twitter:creator">
     <meta content="https://indianexpress.com/" name="twitter:url"/>
     <meta content="Latest News Today, Breaking News, India News, Top Headlines| The Indian Express" name="twitter:title"/>
     <meta content="Get the latest news today, breaking news, and top news headlines updates from India and around the world. Stay updated on politics, business, sports, entertainment, and more with The Indian Express." name="twitter:description"/>
     <meta content="https://indianexpress.com/wp-content/themes/indianexpress/images/IE-OGimage.jpg" property="twitter:image">
      <meta content="image/jpeg" property="twitter:image:type">
       <meta content="1200" property="twitter:image:width">
        <meta content="667" property="twitter:image:height">
         <meta content="en" itemprop="inLanguage"/>
         <meta content="Latest News Today, Breaking News, India News, Top Headlines| The Indian Express" itemprop="name"/>
         <meta content="https://indianexpress.com/" itemprop="mainEntityOfPage">
          <meta content="https://indianexpress.com/" itemprop="url"/>
          <meta content="Latest News Today, Breaking News, India News, Top Headlines| The Indian Express" itemprop="headline"/>
          <meta content="Get the latest news today, breaking news, and top news headlines updates from India and around the world. Stay updated on politics, business, sports, entertainment, and more with The Indian Express." itemprop="description"/>
          <meta content="News, Latest News, Breaking News, Live News, India News, News Online, News Headlines, News Today, English News, Top Stories" itemprop="keywords"/>
          <script type="application/ld+json">
           {"@context":"https:\/\/schema.org","@type":"WebPage","name":"Latest News Today, Breaking News, India News, Top Headlines| The Indian Express","description":"Get the latest news today, breaking news, and top news headlines updates from India and around the world. Stay updated on politics, business, sports, entertainment, and more with The Indian Express.","keywords":"News, Latest News, Breaking News, Live News, India News, News Online, News Headlines, News Today, English News, Top Stories","url":"https:\/\/indianexpress.com\/","mainContentOFPage":"News","inLanguage":"en","lastReviewed":"2026-06-16"}
          </script>
          <script type="application/ld+json">
           {
			"@context":"https://schema.org/",
			"@type":"ViewAction",
			"target":{
				"type":"EntryPoint",
				"urlTemplate":"https://indexpress.page.link/shareDL"
			}
		}
          </script>
          <meta content="00120a3a212c33eda15559fea6d0731769fd82f538180bd0a2dbe12991312ab4" name="ahrefs-site-verification"/>
          <meta content="NOODP" name="robots">
           <meta content="MJ12_ad7db024-a46c-482a-bb2f-e1ae09432a65" name="majestic-site-verification"/>
           <script>
            window.criteo_pubtag = window.criteo_pubtag || {};window.criteo_pubtag.disableSync = true;
           </script>
           <meta content="max-image-preview:large" name="robots">
            <style>
             img:is([sizes="auto" i], [sizes^="auto," i]) { contain-intrinsic-size: 3000px 1500px }
            </style>
            <script>
             let iersisAbtesting='yes';
			let iersCampName='v2-campaign-sub-1-4-20260514';
			let iersACohert=100;
			let iersShowAwsRegisteredUser='yes';
			let iersLoyaltyType='{"enable_aws_loyalty":"sessionLoyalty","casual":"1","repeat":"1","engaged":"1","loyal":"1","brandlover":"1"}';
			let iersCampNameRegistered='v2-campaign-reg-1-4-20260511';
			let iersACohertRegistered=50;
			let iersRemainingLoyaltyType='{"enable_aws_loyalty":"sessionLoyalty","casual":"1","repeat":"1","engaged":"1","loyal":"1","brandlover":"1"}';
			let iersCampNameRemainingRegistered='v2-campaign-reg-1-4-20260511';
			let iersACohertRemainingRegistered='50';
			let iersVersionSubscriber='sub-1.4';
			let iersVersion1Registered='reg-1.4';
			let iersVersion2Registered='reg-1.4';
			let iersPageLoadEvent ='yes';
			let iersShowAwsAnonymousUser='yes';
			let iersCampNameAnonymous='v2-campaign-ano-1-0-20260515';
			let iersACohertAnonymous='5';
			let iersVersionAnonymous='ano-1.0';
			let iersUserType="anonymous_user",iersVersion="",currentURLIers=window.location.href;var urlIers=new URL(currentURLIers),urlKeyIers=urlIers.searchParams.get("taboolatype");let iersRegisteredUsersLoyaltyPass=!1,iersNonLoyaltyRegisteredUser=!1,iersRegisterUser2_0=!1,iersABtestCase=!1,iersSavedSegmentName=iersGetWithExpiry("iers_segment_name"),iersSegmentName="",iersUserPlanDetails=[],iersUserDetails=!1,iersUserState="guest";null!==iersSavedSegmentName&&(iersSegmentName=iersSavedSegmentName.name);let iersSavedUserTopSections=iersGetWithExpiry("iers_user_top_sections"),iersUserTopSections=[];null!==iersSavedUserTopSections&&(iersUserTopSections=iersSavedUserTopSections.name);let iersLoggedinUserDetails=null,iers_allocation_done=!1,iers_isAwsUser=!1,iers_resolveAllocation=[];function iersIsAwsUsersList(){return new Promise(e=>{if(iers_allocation_done)return e(iers_isAwsUser);iers_resolveAllocation.push(e)})}function iersGlobalGetCookie(e){let r=e+"=",s=decodeURIComponent(document.cookie).split(";");for(let e=0;e<s.length;e++){let i=s[e];for(;" "==i.charAt(0);)i=i.substring(1);if(0==i.indexOf(r))return i.substring(r.length,i.length)}return""}function iersGlobalUndefinedCheck(e){let r=!1;return void 0!==e&&""!==e&&null!==e&&(r=!0),r}function iersCheckIfSubscriberAllowed(e){let r=!1;return!0===[10346934,209186,15268894,209185,203493,208633,208634,208635,208636,208637,208638,208639,208640,208641,208642,208643,208644,208645,208646,208648,208649,208650,13232261,14839323,3432583,10521544,8105709,785651,6805839,4726075,4382867,10095307,35,3640408,49,6591,19716,6564,8481,9415574,208807,13232532].includes(e)&&(r=!0),r}function iersCheckIfSubscriberEmailAllowed(e){return"string"==typeof e&&""!==e&&(e.endsWith("@indianexpress.com")||e.endsWith("@expressindia.com"))}function iersGetAlphaUsers(e,r){return(!0===iersCheckIfSubscriberAllowed(e)||!0===iersCheckIfSubscriberEmailAllowed(r))&&(iersUserType="alpha_user",!0)}async function iersIsAwsSubscriber(e){if(null!==iersLoggedinUserDetails){let e=iersHardcodedEmails(iersLoggedinUserDetails.user_email);if(!1!==e)return e}let r="subscriber_personalization",s=50;"undefined"!=typeof iersCampName&&iersCampName&&"undefined"!=typeof iersACohert&&iersACohert&&(r=iersCampName,s=iersACohert);let i=await iersassignVariantFromSsoid(e,s);return iersUserType="variant_personalize","B"===i&&(iersUserType="control_taboola"),null!=urlKeyIers&&""!==urlKeyIers&&(iersUserType="variant_personalize",i="A","control_taboola"===urlKeyIers&&(iersUserType="control_taboola",i="B")),i}function iersstr2ab(e){const r=new ArrayBuffer(e.length),s=new Uint8Array(r);for(let r=0;r<e.length;r++)s[r]=e.charCodeAt(r);return r}function iersab2hex(e){const r=[],s=new Uint8Array(e);for(let e=0;e<s.length;e++){const i=s[e].toString(16).padStart(2,"0");r.push(i)}return r.join("")}async function ierssha256Hex(e){return iersab2hex(await crypto.subtle.digest("SHA-256",iersstr2ab(e)))}async function iersassignVariantFromSsoid(e=null,r=10){if(r<0||r>100)throw new Error("percentageA must be between 0 and 100");let s=e?String(e).trim():"";return iersHexMod(await ierssha256Hex(s),100)<r?"A":"B"}function iersHexMod(e,r){let s=0;for(let i=0;i<e.length;i++)s=(16*s+parseInt(e[i],16))%r;return s}function iersGetVersion(){let e=iersGlobalGetCookie("ev_user_state"),r="";return"subscriber"===e?r=iersVersionSubscriber:"registered"===e?(r=iersVersion1Registered,!0===iersRegisterUser2_0&&(r=iersVersion2Registered)):"guest"===e&&(r=iersVersionAnonymous),iersVersion=r,r}function iersGetLoyaltyInfo(){let e=iersGlobalGetCookie("userLoyaltyBand"),r=!1;if(!0===iersGlobalUndefinedCheck(e))try{let s=JSON.parse(e);!0===iersGlobalUndefinedCheck(s)&&(s=JSON.parse(s),s&&"object"==typeof s&&(r={pvLoyalty:s.plb,sessionLoyalty:s.slb}))}catch(e){console.error("Unable to parse userLoyaltyBand",e)}return r}async function iersIsAwsRegisteredUser(e,r,s){if(null!==iersLoggedinUserDetails){let e=iersHardcodedEmails(iersLoggedinUserDetails.user_email);if(!1!==e)return e}let i=await iersassignVariantFromSsoid(e,s);return iersUserType="variant_personalize","B"===i&&(iersUserType="control_taboola"),null!=urlKeyIers&&""!==urlKeyIers&&(iersUserType="variant_personalize",i="A","control_taboola"===urlKeyIers&&(iersUserType="control_taboola",i="B")),i}function iersSetWithExpiry(e,r,s){const i={value:r,expiry:(new Date).getTime()+s};localStorage.setItem(e,JSON.stringify(i))}function iersGetWithExpiry(e){const r=localStorage.getItem(e);if(!r)return null;const s=JSON.parse(r);return(new Date).getTime()>s.expiry?(localStorage.removeItem(e),null):s.value}function iersHardcodedEmails(e){return"string"==typeof e&&""!==e&&void 0!==e&&("developregister@mailinator.com"===(e=e.toLowerCase())||"subscribeharshitpreprod@mailinator.com"===e?(iersUserType="variant_personalize","A"):("developregister1@mailinator.com"===e||"newsubscribepreprod@mailinator.com"===e)&&(iersUserType="control_taboola","B"))}window.addEventListener("iers_allocation_done",e=>{iers_allocation_done=!0,iers_resolveAllocation.length>0&&iers_resolveAllocation.forEach(function(e){e(iers_isAwsUser)})},{once:!0});
            </script>
            <link crossorigin="" href="https://fonts.gstatic.com/" rel="preconnect"/>
            <link href="https://www.googletagservices.com/" rel="preconnect">
             <link href="https://ads.pubmatic.com/" rel="preconnect"/>
             <link href="https://tpc.googlesyndication.com/" rel="preconnect"/>
             <link href="https://securepubads.g.doubleclick.net/" rel="preconnect"/>
             <link href="https://www.google.com/" rel="preconnect"/>
             <link href="https://googleads.g.doubleclick.net/" rel="preconnect"/>
             <link href="https://ads.pubmatic.com/" rel="preconnect"/>
             <link href="https://www.google-analytics.com/" rel="preconnect"/>
             <link href="https://apis.google.com/" rel="preconnect"/>
             <link href="https://www.googletagmanager.com/" rel="preconnect"/>
             <link href="https://cdn.moengage.com/" rel="preconnect"/>
             <link href="https://sb.scorecardresearch.com/" rel="preconnect"/>
             <link href="https://ua.indianexpress.com/" rel="preconnect"/>
             <link crossorigin="" href="https://fonts.gstatic.com/" rel="dns-prefetch"/>
             <link href="https://www.googletagservices.com/" rel="dns-prefetch">
              <link href="https://ads.pubmatic.com/" rel="dns-prefetch"/>
              <link href="https://tpc.googlesyndication.com/" rel="dns-prefetch"/>
              <link href="https://securepubads.g.doubleclick.net/" rel="dns-prefetch"/>
              <link href="https://www.google.com/" rel="dns-prefetch"/>
              <link href="https://googleads.g.doubleclick.net/" rel="dns-prefetch"/>
              <link href="https://ads.pubmatic.com/" rel="dns-prefetch"/>
              <link href="https://www.google-analytics.com/" rel="dns-prefetch"/>
              <link href="https://apis.google.com/" rel="dns-prefetch"/>
              <link href="https://www.googletagmanager.com/" rel="dns-prefetch"/>
              <link href="https://cdn.moengage.com/" rel="dns-prefetch"/>
              <link href="https://sb.scorecardresearch.com/" rel="dns-prefetch"/>
              <link href="https://ua.indianexpress.com/" rel="dns-prefetch"/>
              <link href="https://rtbcdn.andbeyond.media" rel="preconnect"/>
              <link href="https://rtbcdn.andbeyond.media" rel="dns-prefetch"/>
              <link href="https://rtbpass-us.andbeyond.media" rel="preconnect"/>
              <link href="https://rtbpass-us.andbeyond.media" rel="dns-prefetch"/>
              <link crossorigin="" href="https://cdn.taboola.com" rel="preconnect"/>
              <link href="//cdn.taboola.com" rel="dns-prefetch"/>
              <link href="https://static.chartbeat.com/" rel="preconnect"/>
              <link href="https://static.chartbeat.com/" rel="dns-prefetch"/>
              <link as="font" crossorigin="" href="https://fonts.gstatic.com/s/ptserif/v18/EJRVQgYoZZY2vCFuvAFWzr8.woff2" rel="preload" type="font/woff2"/>
              <link as="font" crossorigin="" href="https://fonts.gstatic.com/s/roboto/v47/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmUiAo.woff2" rel="preload" type="font/woff2"/>
              <link as="font" crossorigin="" href="https://fonts.gstatic.com/s/ptserif/v18/EJRSQgYoZZY2vCFuvAnt66qSVys.woff2" rel="preload" type="font/woff2"/>
              <link as="font" crossorigin="" href="https://fonts.gstatic.com/s/roboto/v47/KFO7CnqEu92Fr1ME7kSn66aGLdTylUAMa3yUBHMdazQ.woff2" rel="preload" type="font/woff2"/>
              <style>
               @font-face{font-family:'PT Serif';font-style:normal;font-weight:400;font-display:swap;src:url(https://fonts.gstatic.com/s/ptserif/v18/EJRVQgYoZZY2vCFuvAFWzr8.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:Roboto;font-style:normal;font-weight:700;font-stretch:100%;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v47/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjalmUiAo.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:'PT Serif';font-style:normal;font-weight:700;font-display:swap;src:url(https://fonts.gstatic.com/s/ptserif/v18/EJRSQgYoZZY2vCFuvAnt66qSVys.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:Roboto;font-style:normal;font-weight:400;font-stretch:100%;font-display:swap;src:url(https://fonts.gstatic.com/s/roboto/v47/KFO7CnqEu92Fr1ME7kSn66aGLdTylUAMa3yUBHMdazQ.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD}
              </style>
              <!-- Jetpack Site Verification Tags -->
              <meta content="GksxYjGFLX8yIx8g5v-Jg5XueVMsv23jAO2UE8hpetM" name="google-site-verification">
               <meta content="CCA9DA5B985004F4462DA743E776C636" name="msvalidate.01"/>
               <style data-id="inline-css-060620261621" type="text/css">
                @charset 'UTF-8';

In [9]:
script = soup.find("div",class_= "top-news")
print(script)

None

##  Pb375 Write a program for web scrapping using BeautifulSoup to scrape the following details from the given link and make a data frame using that scraped data from the page in a given link. You will find 30 news articles with fact checks on this page. You need to scrape the following details from all the articles andstore that in a data frame. Statement of News, Date of News, Source of News.
Link: https://www.politifact.com/factchecks

In [10]:
response = requests.get("https://www.politifact.com/factchecks")
print(response)

<Response [200]>

In [12]:
data = response.text
soup = bs4.BeautifulSoup(data, "html.parser")
print(soup.prettify())

<!DOCTYPE html>
<html dir="ltr" lang="en-US">
 <head>
  <meta charset="utf-8"/>
  <meta content="ie=edge" http-equiv="x-ua-compatible"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title>
   Fact-checks | PolitiFact
  </title>
  <meta content="PolitiFact is a fact-checking website that rates the accuracy of claims by elected officials and others on its Truth-O-Meter." name="description">
   <meta content="all" name="robots">
    <meta content="PolitiFact" name="publisher"/>
    <meta content="PolitiFact" name="twitter:username">
     <meta content="summary" name="twitter:card">
      <meta content="PolitiFact" name="twitter:site"/>
      <meta content="" name="twitter:url">
       <meta content="" name="twitter:title"/>
       <meta content="PolitiFact is a fact-checking website that rates the accuracy of claims by elected officials and others on its Truth-O-Meter." name="twitter:description"/>
       <meta content="vrxxsw8mwnf2pxgnwxvgsn4g93w3vm" name="facebook-domain-verification"/>
       <link href="https://static.politifact.com/images/favicon.ico" rel="shortcut icon" type="image/ico"/>
       <link href="https://static.politifact.com/images/favicon.png" rel="icon" type="image/png"/>
       <link href="https://static.politifact.com/images/apple-touch-icon.png" rel="apple-touch-icon"/>
       <link href="/rss/social/" rel="alternate" title="Latest Fact-checks and Articles" type="application/rss+xml">
        <link href="/rss/factchecks/" rel="alternate" title="Latest Fact-checks" type="application/rss+xml">
         <script src="https://static.politifact.com/js/sharethefacts-v1.js">
         </script>
         <script src="//d283fm003ll1xs.cloudfront.net/script.js" type="text/javascript">
         </script>
         <script>
          !(function () { window.googletag = window.googletag || {}; window.vmpbjs = window.vmpbjs || {}; window.vpb = window.vpb || {}; vpb.cmd = vpb.cmd || []; vpb.st=Date.now();  vpb.fastLoad = true; googletag.cmd = googletag.cmd || []; vmpbjs.cmd = vmpbjs.cmd || []; var cmds = []; try{ cmds = googletag.cmd.slice(0); googletag.cmd.length = 0; }catch(e){} var ready = false; function exec(cb) { return cb.call(googletag); } var overriden = false; googletag.cmd.push(function () { overriden = true; googletag.cmd.unshift = function (cb) { if (ready) { return exec(cb); } cmds.unshift(cb); if (cb._startgpt) { ready = true; for (var k = 0; k < cmds.length; k++) { exec(cmds[k]); } } }; googletag.cmd.push = function (cb) { if (ready) { return exec(cb); } cmds.push(cb); }; }); if(!overriden){ googletag.cmd.push = function (cb) { cmds.push(cb); }; googletag.cmd.unshift = function (cb) { cmds.unshift(cb); if (cb._startgpt) { ready = true; if (googletag.apiReady) { cmds.forEach(function (cb) { googletag.cmd.push(cb); }); } else { googletag.cmd = cmds; } } }; } var dayMs = 36e5, cb = parseInt(Date.now() / dayMs), vpbSrc = '//player.hbmp.ops.co/prebidlink/' + cb + '/wrapper_hb_779253_23204.js', pbSrc = vpbSrc.replace('wrapper_hb', 'hb'), gptSrc = '//securepubads.g.doubleclick.net/tag/js/gpt.js', c = document.head || document.body || document.documentElement; function loadScript(src, cb) { var s = document.createElement('script'); s.src = src; s.defer=false; c.appendChild(s); s.onload = cb; s.onerror = function(){ var fn = function(){}; fn._startgpt = true; googletag.cmd.unshift(fn); }; return s; } loadScript(pbSrc); loadScript(gptSrc); loadScript(vpbSrc); })()
         </script>
         <script>
          window.googletag = window.googletag || {cmd: []};
  googletag.cmd.push(function() {
    const sizeMapping = googletag.sizeMapping()
        .addSize([1440, 0], [
            [970,90],
            [970,250],
            [728,90],
        ])
        .addSize([1024, 0], [
            [728,90],
            [320,100],
        ])
        .addSize([768, 0], [
            [320, 50],
            [300, 50],
        ])
        .addSize([0, 0], [
            [320, 50],
			[300, 50],
        ])
        .build();
    googletag.defineSlot('/25722649/Politifact/BottomLeaderboard_Adhesion', [[300,50],[320,50],[728,90]], 'BottomLeaderboard_Adhesion')
      .defineSizeMapping(sizeMapping)
      .addService(googletag.pubads());
    googletag.defineSlot('/25722649/Politifact/Politifact_BottomLeaderboard', [[320,50],[728,90]], 'BottomLeaderboard')
      .defineSizeMapping(sizeMapping)
      .addService(googletag.pubads());
    googletag.defineSlot('/25722649/Politifact/Politifact_MiddleRectangle', [[300,250]], 'MiddleRectangle')
             .addService(googletag.pubads());
    googletag.defineSlot('/25722649/Politifact/Politifact_TopLeaderboard', [[320,50],[728,90]], 'TopLeaderboard')
      .defineSizeMapping(sizeMapping)
      .addService(googletag.pubads());
    googletag.defineSlot('/25722649/Politifact/Politifact_TopMedRect', [[300,250],[300,600]], 'TopMedRect')
             .addService(googletag.pubads());
    googletag.defineSlot('/25722649/Politifact/SmartNewsFeed', [[300,250]], 'SmartNewsFeed')
             .addService(googletag.pubads());

    googletag.pubads().enableSingleRequest();
    googletag.enableServices();
  });
         </script>
         <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-35156640-2">
         </script>
         <script>
          window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-35156640-2');
         </script>
         <script async="" src="https://www.googletagmanager.com/gtag/js?id=G-EDXB0TJGGY">
         </script>
         <script>
          window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-EDXB0TJGGY');
         </script>
         <script async="" id="ebx" src="//applets.ebxcdn.com/ebx.js">
         </script>
         <div id="fb-root">
         </div>
         <script>
          (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
         </script>
         <!-- End Facebook Pixel Code -->
         <noscript>
          <img height="1" src="//www.facebook.com/tr?id=292850974235854&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/>
         </noscript>
         <link href="https://static.politifact.com/assets/main-CiDydm0l.css" rel="stylesheet">
          <style>
           .m-notfound{padding-top:2.5rem;padding-bottom:3.5rem}@media print, screen and (min-width: 48em){.m-notfound{padding-top:5rem;padding-bottom:6rem}}.m-notfound__title{margin-bottom:2.5rem;text-align:center}@media print, screen and (min-width: 48em){.m-notfound__content{display:-webkit-box;display:-ms-flexbox;display:flex}}.m-notfound__image{margin-bottom:1.5rem;margin-left:auto;margin-right:auto;max-width:10rem}@media print, screen and (min-width: 48em){.m-notfound__image{-webkit-box-flex:0;-ms-flex:0 0 13.75rem;flex:0 0 13.75rem;max-width:none}}.m-notfound__body{padding-top:.5rem}@media print, screen and (min-width: 48em){.m-notfound__body{padding-left:2rem}}.m-notfound__body p{margin-top:0}
          </style>
         </link>
        </link>
       </link>
      </meta>
     </meta>
    </meta>
   </meta>
  </meta>
 </head>
 <body class="" data-role="page">
  <div class="global-wrapper" id="top">
   <header class="o-header">
    <div class="o-header__inner">
     <div class="o-header__branding">
      <a href="/">
       <span class="m-branding">
        <span class="m-branding__logo">
         <svg class="c-icon">
          <use xlink:href="#svg_logo-plain">
          </use>
         </svg>
        </span>
        <span class="m-branding__subline">
         <span class="m-branding__claim">
          The Poynter Institute
         </span>
        </span>
       </span>
      </a>
     </div>
     <div class="o-header__menu">
      <a class="c-burger" data-menu-toggle="" href="#">
       <span class="c-burger__lines">
       </span>
       <span class="c-burger__value">
        Menu
       </span>
      </a>
     </div>
     <div class="o-header__donate">
      <a class="c-button c-button--small show-for-large" href="/membership/">
       Donate
      </a>
     </div>
    </div>
    <div class="t-menu" data-menu="">
     <div class="t-menu__content">
      <div class="o-menu-list">
       <div class="o-menu-list__inner">
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_1" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_1" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_1" role="tab">
           State Editions
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_1" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/california/">
              California
             </a>
            </li>
            <li>
             <a href="/florida/">
              Florida
             </a>
            </li>
            <li>
             <a href="/iowa/">
              Iowa
             </a>
            </li>
            <li>
             <a href="/michigan/">
              Michigan
             </a>
            </li>
            <li>
             <a href="/new-hampshire/">
              New Hampshire
             </a>
            </li>
            <li>
             <a href="/new-york/">
              New York
             </a>
            </li>
            <li>
             <a href="/north-carolina/">
              North Carolina
             </a>
            </li>
            <li>
             <a href="/pennsylvania/">
              Pennsylvania
             </a>
            </li>
            <li>
             <a href="/texas/">
              Texas
             </a>
            </li>
            <li>
             <a href="/west-virginia/">
              West Virginia
             </a>
            </li>
            <li>
             <a href="/wisconsin/">
              Wisconsin
             </a>
            </li>
            <li>
            </li>
           </ul>
          </div>
         </div>
        </div>
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_2" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_2" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_2" role="tab">
           Issues
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_2" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <strong>
              <a href="/issues/">
               All Issues
              </a>
             </strong>
            </li>
            <li>
             <a href="/factchecks/list/?speaker_type=SOCIAL">
              Online hoaxes
             </a>
            </li>
            <li>
             <a href="/coronavirus/">
              Coronavirus
             </a>
            </li>
            <li>
             <a href="/health-check/">
              Health Care
             </a>
            </li>
            <li>
             <a href="/immigration/">
              Immigration
             </a>
            </li>
            <li>
             <a href="https://www.politifact.com/article/2022/jun/09/political-extremism-public-square-resource-journal/">
              Extremism
             </a>
            </li>
            <li>
             <a href="/taxes/">
              Taxes
             </a>
            </li>
            <li>
             <a href="/marijuana/">
              Marijuana
             </a>
            </li>
            <li>
             <a href="/environment/">
              Environment
             </a>
            </li>
            <li>
             <a href="/crime/">
              Crime
             </a>
            </li>
            <li>
             <a href="/guns/">
              Guns
             </a>
            </li>
            <li>
             <a href="/foreign-policy/">
              Foreign Policy
             </a>
            </li>
            <li>
             <a href="/lgbtq/">
              LGBTQ+
             </a>
            </li>
           </ul>
          </div>
         </div>
        </div>
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_3" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_3" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_3" role="tab">
           People
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_3" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/personalities/donald-trump/">
              Donald Trump
             </a>
            </li>
            <li>
             <a href="/personalities/jd-vance/">
              JD Vance
             </a>
            </li>
            <li>
             <a href="/personalities/mitch-mcconnell/">
              Mitch McConnell
             </a>
            </li>
            <li>
             <a href="/personalities/mike-johnson/">
              Mike Johnson
             </a>
            </li>
            <li>
             <a href="/personalities/joe-biden/">
              Joe Biden
             </a>
            </li>
           </ul>
          </div>
         </div>
        </div>
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_4" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_4" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_4" role="tab">
           Media
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_4" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/punditfact/">
              PunditFact
             </a>
            </li>
            <li>
             <a href="/personalities/tucker-carlson/">
              Tucker Carlson
             </a>
            </li>
            <li>
             <a href="/personalities/sean-hannity/">
              Sean Hannity
             </a>
            </li>
            <li>
             <a href="/personalities/rachel-maddow/">
              Rachel Maddow
             </a>
            </li>
            <li>
             <a href="/personalities/blog-posting/">
              Bloggers
             </a>
            </li>
            <li>
             <a href="/videos/">
              PolitiFact Videos
             </a>
            </li>
           </ul>
          </div>
         </div>
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_5" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_5" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_5" role="tab">
           Campaigns
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_5" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/elections/">
              2024 Elections
             </a>
            </li>
           </ul>
          </div>
         </div>
        </div>
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_6" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_6" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_6" role="tab">
           Truth-o-Meter
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_6" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/factchecks/list/?ruling=true">
              True
             </a>
            </li>
            <li>
             <a href="/factchecks/list/?ruling=mostly-true">
              Mostly True
             </a>
            </li>
            <li>
             <a href="/factchecks/list/?ruling=half-true">
              Half True
             </a>
            </li>
            <li>
             <a href="/factchecks/list/?ruling=barely-true">
              Mostly False
             </a>
            </li>
            <li>
             <a href="/factchecks/list/?ruling=false">
              False
             </a>
            </li>
            <li>
             <a href="/factchecks/list/?ruling=pants-fire">
              Pants on Fire
             </a>
            </li>
           </ul>
          </div>
         </div>
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_7" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_7" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_7" role="tab">
           Promises
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_7" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/truth-o-meter/promises/maga-meter-tracking-donald-trumps-2024-promises/?ruling=true">
              MAGA-Meter
             </a>
            </li>
            <li>
             <a href="/truth-o-meter/promises/biden-promise-tracker/?ruling=true">
              Biden Promise Tracker
             </a>
            </li>
            <li>
             <a href="/truth-o-meter/promises/trumpometer/?ruling=true">
              Trump-O-Meter
             </a>
            </li>
            <li>
             <a href="/truth-o-meter/promises/obameter/?ruling=true">
              Obameter
             </a>
             <li>
              <a href="/truth-o-meter/promises/list/">
               Latest Promises
              </a>
             </li>
            </li>
           </ul>
          </div>
         </div>
        </div>
        <div class="o-menu-list__item">
         <div aria-multiselectable="true" class="m-togglist" role="tablist">
          <input class="m-togglist__checkbox show-for-sr" id="togglist_8" name="" type="checkbox" value=""/>
          <label aria-controls="togglist_8" aria-expanded="false" aria-selected="true" class="m-togglist__label" for="togglist_8" role="tab">
           About Us
          </label>
          <div aria-hidden="true" aria-labelledby="togglist_8" class="m-togglist__panel" role="tabpanel">
           <ul class="m-togglist__list">
            <li>
             <a href="/article/2018/feb/12/principles-truth-o-meter-politifacts-methodology-i/ ">
              Our Process
             </a>
            </li>
            <li>
             <a href="/staff/">
              Our Staff
             </a>
            </li>
            <li>
             <a href="/espanol/">
              En Español
             </a>
            </li>
            <li>
             <a href="/who-pays-for-politifact/">
              Who pays for PolitiFact?
             </a>
            </li>
            <li>

In [ ]:
script = soup.find("li", {'class': "o-listicle__item"})
print(script)

<li class="o-listicle__item">
<article class="m-statement m-statement--is-medium m-statement--fire">
<div class="m-statement__author">
<div class="m-statement__avatar">
<div class="m-statement__image">
<div class="c-image" style="padding-top: 119.27710843373494%;">
<img class="c-image__thumb" height="99" src="https://static.politifact.com/CACHE/images/politifact/mugs/Josh_Hokit/49efd6a65126c0bdfda0024da2a6d5b0.jpg" width="83"/>
<picture>
<img class="c-image__original" height="178" src="https://static.politifact.com/CACHE/images/politifact/mugs/Josh_Hokit/a834b2ca08e17aa39b4975fa84d2f462.jpg" width="166"/>
</picture>
</div>
</div>
</div>
<div class="m-statement__meta">
<a class="m-statement__name" href="/personalities/josh-hokit/" title="Josh Hokit">
                    Josh Hokit
                  </a>
<div class="m-statement__desc">
                    stated on June 14, 2026 in a UFC event at the White House:
                  </div>
</div>
</div>
<div class="m-statement__content">
<div class="m-statement__body">
<div class="m-statement__quote-wrap">
<div class="m-statement__quote">
<a href="/factchecks/2026/jun/15/josh-hokit/josh-hokit-ufc-white-house-michelle-obama/">

                        “Michelle Obama is a man.”

                      </a>
</div>
</div>
<div class="m-statement__meter">
<div class="c-image" style="padding-top: 89.49771689497716%;">
<img alt="pants-fire" class="c-image__thumb" height="196" src="https://static.politifact.com/img/meter-pants-fire-th.jpg" width="219"/>
<picture>
<img alt="pants-fire" class="c-image__original" height="196" src="https://static.politifact.com/img/meter-pants-fire.jpg" width="219"/>
</picture>
</div>
</div>
<footer class="m-statement__footer">
                    By Loreben Tuquero • June 15, 2026
                  </footer>
</div>
</div>
</article>
</li>

In [22]:
print("News headline : ",script.find("a").text)
print("Date of news : ",script.find("footer").text.split("•")[1])
print("Source of news : ",script.find("a")['href'])

News headline :
                    Josh Hokit

Date of news :   June 15, 2026

Source of news :  /personalities/josh-hokit/

In [23]:
script = soup.findAll("li", {'class': "o-listicle__item"})
print(len(script))

30

C:\Users\dapat\AppData\Local\Temp\ipykernel_11524\1262686797.py:1: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  script = soup.findAll("li", {'class': "o-listicle__item"})

In [27]:
list_of_news = []
for i in script:
    df = {
        "News headline" : i.find("a").text.strip(),
        "Date of news" : i.find("footer").text.split("•")[1].strip(),
        "Source of news" : i.find("a")['href']
    }
    list_of_news.append(df)
    print(df)

print(len(list_of_news))

{'News headline': 'Josh Hokit', 'Date of news': 'June 15, 2026', 'Source of news': '/personalities/josh-hokit/'}
{'News headline': 'Elizabeth Warren', 'Date of news': 'June 12, 2026', 'Source of news': '/personalities/elizabeth-warren/'}
{'News headline': 'Donald Trump', 'Date of news': 'June 12, 2026', 'Source of news': '/personalities/donald-trump/'}
{'News headline': 'Graham Platner', 'Date of news': 'June 10, 2026', 'Source of news': '/personalities/graham-platner/'}
{'News headline': 'Donald Trump', 'Date of news': 'June 8, 2026', 'Source of news': '/personalities/donald-trump/'}
{'News headline': 'X posts', 'Date of news': 'June 8, 2026', 'Source of news': '/personalities/tweets/'}
{'News headline': 'X posts', 'Date of news': 'June 8, 2026', 'Source of news': '/personalities/tweets/'}
{'News headline': 'Social Media', 'Date of news': 'June 8, 2026', 'Source of news': '/personalities/social-media/'}
{'News headline': 'X posts', 'Date of news': 'June 8, 2026', 'Source of news': '/personalities/tweets/'}
{'News headline': 'Ashley Hinson', 'Date of news': 'June 5, 2026', 'Source of news': '/personalities/ashley-hinson/'}
{'News headline': 'John Kagia', 'Date of news': 'June 5, 2026', 'Source of news': '/personalities/john-kagia/'}
{'News headline': 'Mallory McMorrow', 'Date of news': 'June 4, 2026', 'Source of news': '/personalities/mallory-mcmorrow/'}
{'News headline': 'James Talarico', 'Date of news': 'June 3, 2026', 'Source of news': '/personalities/james-talarico/'}
{'News headline': 'Donald Trump', 'Date of news': 'June 3, 2026', 'Source of news': '/personalities/donald-trump/'}
{'News headline': 'Social Media', 'Date of news': 'June 1, 2026', 'Source of news': '/personalities/social-media/'}
{'News headline': 'TikTok posts', 'Date of news': 'May 28, 2026', 'Source of news': '/personalities/tiktok-posts/'}
{'News headline': 'Ken Paxton', 'Date of news': 'May 28, 2026', 'Source of news': '/personalities/ken-paxton/'}
{'News headline': 'Ken Paxton', 'Date of news': 'May 27, 2026', 'Source of news': '/personalities/ken-paxton/'}
{'News headline': 'Marco Rubio', 'Date of news': 'May 22, 2026', 'Source of news': '/personalities/marco-rubio/'}
{'News headline': 'Kirsten Gillibrand', 'Date of news': 'May 21, 2026', 'Source of news': '/personalities/kirsten-gillibrand/'}
{'News headline': 'Donald Trump', 'Date of news': 'May 20, 2026', 'Source of news': '/personalities/donald-trump/'}
{'News headline': 'Social Media', 'Date of news': 'May 20, 2026', 'Source of news': '/personalities/social-media/'}
{'News headline': 'X posts', 'Date of news': 'May 15, 2026', 'Source of news': '/personalities/tweets/'}
{'News headline': 'X posts', 'Date of news': 'May 14, 2026', 'Source of news': '/personalities/tweets/'}
{'News headline': 'Kathy Castor', 'Date of news': 'May 14, 2026', 'Source of news': '/personalities/kathy-castor/'}
{'News headline': 'Vivek Ramaswamy', 'Date of news': 'May 13, 2026', 'Source of news': '/personalities/vivek-ramaswamy/'}
{'News headline': 'TikTok posts', 'Date of news': 'May 13, 2026', 'Source of news': '/personalities/tiktok-posts/'}
{'News headline': 'Christine Quinn', 'Date of news': 'May 11, 2026', 'Source of news': '/personalities/christine-quinn/'}
{'News headline': 'Nicholas Langworthy', 'Date of news': 'May 11, 2026', 'Source of news': '/personalities/nicholas-langworthy/'}
{'News headline': 'Donald Trump', 'Date of news': 'May 8, 2026', 'Source of news': '/personalities/donald-trump/'}
30

In [29]:
import pandas as pd
df = pd.DataFrame(list_of_news)
df

          News headline   Date of news                       Source of news
0            Josh Hokit  June 15, 2026           /personalities/josh-hokit/
1      Elizabeth Warren  June 12, 2026     /personalities/elizabeth-warren/
2          Donald Trump  June 12, 2026         /personalities/donald-trump/
3        Graham Platner  June 10, 2026       /personalities/graham-platner/
4          Donald Trump   June 8, 2026         /personalities/donald-trump/
5               X posts   June 8, 2026               /personalities/tweets/
6               X posts   June 8, 2026               /personalities/tweets/
7          Social Media   June 8, 2026         /personalities/social-media/
8               X posts   June 8, 2026               /personalities/tweets/
9         Ashley Hinson   June 5, 2026        /personalities/ashley-hinson/
10           John Kagia   June 5, 2026           /personalities/john-kagia/
11     Mallory McMorrow   June 4, 2026     /personalities/mallory-mcmorrow/
12       James Talarico   June 3, 2026       /personalities/james-talarico/
13         Donald Trump   June 3, 2026         /personalities/donald-trump/
14         Social Media   June 1, 2026         /personalities/social-media/
15         TikTok posts   May 28, 2026         /personalities/tiktok-posts/
16           Ken Paxton   May 28, 2026           /personalities/ken-paxton/
17           Ken Paxton   May 27, 2026           /personalities/ken-paxton/
18          Marco Rubio   May 22, 2026          /personalities/marco-rubio/
19   Kirsten Gillibrand   May 21, 2026   /personalities/kirsten-gillibrand/
20         Donald Trump   May 20, 2026         /personalities/donald-trump/
21         Social Media   May 20, 2026         /personalities/social-media/
22              X posts   May 15, 2026               /personalities/tweets/
23              X posts   May 14, 2026               /personalities/tweets/
24         Kathy Castor   May 14, 2026         /personalities/kathy-castor/
25      Vivek Ramaswamy   May 13, 2026      /personalities/vivek-ramaswamy/
26         TikTok posts   May 13, 2026         /personalities/tiktok-posts/
27      Christine Quinn   May 11, 2026      /personalities/christine-quinn/
28  Nicholas Langworthy   May 11, 2026  /personalities/nicholas-langworthy/
29         Donald Trump    May 8, 2026         /personalities/donald-trump/

## Pb376 Write a program of web scrapping using BeautifulSoup to scrape the given data from the following link.On the above link, you’ll find 30 Popular movies. Scrape the Movie Title and Rating of that particular movie and make a Dataframe of the same.
https://editorial.rottentomatoes.com/guide/popular-movies/

In [30]:
response = requests.get("https://editorial.rottentomatoes.com/guide/popular-movies/")
print(response)

<Response [200]>

In [31]:
data = response.text
soup = bs4.BeautifulSoup(data, "html.parser")
print(soup.prettify())

<!DOCTYPE html>
<html lang="en-US">
 <head prefix="og: http://ogp.me/ns# flixstertomatoes: http://ogp.me/ns/apps/flixstertomatoes#">
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <script src="https://www.rottentomatoes.com/rt-common.js?single">
  </script>
  <script id="rt-feature-flags-json" type="application/json">
   {"adsCarouselHP":"true","adsCarouselHPSlug":"rt-sponsored-carousel-list-disney-plus-throwbacks-campaign","adsCarouselOP":"true","adsCarouselOPSlug":"rt-sponsored-carousel-list-disney-plus-throwbacks-campaign","adsMockDLP":"false","adsPages":"none","adsSponsoredOverrideOP":"true","adsSponsoredOverrideOPSlugs":"rt-sponsored-override-op-starz","adsVideoSpotlightHP":"false","artiEnabled":"true","artiSearchNavEnabled":"true","authVerboseLogs":"false","avgTomatometer2025Q4Enabled":"true","bypassCriticValidationEnabled":"false","codeOfConductText2026Q1Enabled":"true","communityWatch2026Q1Enabled":"true","criticPublicationProfile2026Q1Enabled":"true","editorialApiDisabled":"false","jwPlayer2026Q2Enabled":"true","kalshi2026Q1Enabled":"false","legacyBridge":"true","logVerboseEnabled":"false","mobileAppAndroid":"https:\/\/play.google.com\/store\/apps\/details?id=com.rottentomatoes.android","mobileAppIos":"https:\/\/apps.apple.com\/us\/app\/rotten-tomatoes-movies-tv\/id6673916573","mobileAppIosMeta":"app-id=6673916573","profilesFeaturesEnabled":"true","removeFetcherSessionStorage":"true","trafficAndroidEnabled":"true","trafficSafariEnabled":"true","versantMpsEnabled":"true","rtebProxyEnabled":"false","fandangoConsolidation2026Q2Enabled":"false"}
  </script>
  <!-- OneTrust Cookies Consent Notice start for rottentomatoes.com -->
  <script charset="UTF-8" crossorigin="anonymous" data-domain-script="01978557-1604-76a7-ad7c-18216757cf52" integrity="sha384-ZSwMA1OqSOznvxMtYdWlw0CUYqxpHjUOjfz9IcOnQUXvWoX7QfD7wjN7tgv+SpLT" src="https://cdn.cookielaw.org/consent/01978557-1604-76a7-ad7c-18216757cf52/otSDKStub.js" type="text/javascript">
  </script>
  <script type="text/javascript">
   function OptanonWrapper() { }
  </script>
  <!-- OneTrust Cookies Consent Notice end for rottentomatoes.com -->
  <!-- OneTrust IAB US Privacy (USP) -->
  <script ccpa-opt-out-geo="US" ccpa-opt-out-ids="USP" ccpa-opt-out-lspa="false" charset="UTF-8" src="https://cdn.cookielaw.org/opt-out/otCCPAiab.js" type="text/javascript">
  </script>
  <!-- OneTrust IAB US Privacy (USP) end -->
  <meta content="app-id=6673916573" name="apple-itunes-app"/>
  <meta content="See what films are buzzing with RT users this week!" property="og.description">
   <meta content="See what films are buzzing with RT users this week!" name="description"/>
   <meta content="30 Most Popular Movies Right Now: What to Watch In Theaters and Streaming" property="og:title"/>
   <meta content="article" property="og:type"/>
   <meta content="https://editorial.rottentomatoes.com/wp-content/uploads/2026/03/EWKA_Scary_Movie-Rep.jpg?w=600" property="og:image"/>
   <meta content="https://editorial.rottentomatoes.com/guide/popular-movies/" property="og:url"/>
   <meta content="237626" name="editorialID"/>
   <meta content="summary_large_image" name="twitter:card"/>
   <meta content="@rottentomatoes" name="twitter:site"/>
   <meta content="30 Most Popular Movies Right Now: What to Watch In Theaters and Streaming" name="twitter:title"/>
   <meta content="See what films are buzzing with RT users this week!" name="twitter:description"/>
   <meta content="https://editorial.rottentomatoes.com/wp-content/uploads/2026/03/EWKA_Scary_Movie-Rep.jpg?w=600" name="twitter:image"/>
   <title>
    30 Most Popular Movies Right Now: What to Watch In Theaters and Streaming							 | 	Rotten Tomatoes
   </title>
   <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
   <meta content="width=device-width, initial-scale=1" name="viewport"/>
   <link href="https://editorial.rottentomatoes.com/xmlrpc.php" rel="pingback"/>
   <link href="https://editorial.rottentomatoes.com/wp-content/themes/rt-editorial/assets/images/favicon.ico" rel="icon" type="image/x-icon"/>
   <script>
    // Push column to dataLayer
		var dataLayer = dataLayer || [];

		dataLayer.push({
			"post-url": "https:\/\/editorial.rottentomatoes.com\/guide\/popular-movies\/",
			"column": "18",
			"hub":237626,
			"author": "alex-vo",
			"related-tv-series-ids": [],
			"related-movie-ids": [],
			"publication-date": "06\/08\/2026",
			"related-celebrity-ids": [],
			"tags": ""		});
   </script>
   <script>
    var BK = {};
		BK.PageName="https:\/\/editorial.rottentomatoes.com\/guide\/popular-movies\/";
		BK.SiteSection="guide";
		BK.ArticleTags="";
		BK.RelatedMovieId=[];
		BK.RelatedTalentId=[];
		BK.RelatedTVSeriesId=[];

		var mpscall = mpscall || {};
		mpscall = {
			"site":"rottentomatoes-web",
			"field[env]": "production", // Execution environment.
			"type": "guide",
			"cat": "guide|Countdown"		};
		var mpsopts = {
			"host": "app.mps.vsnt.net",
			"updatecorrelator": true
		}
		var mps=mps||{};mps._ext=mps._ext||{};mps._adsheld=[];mps._queue=mps._queue||{};mps._queue.mpsloaded=mps._queue.mpsloaded||[];mps._queue.mpsinit=mps._queue.mpsinit||[];mps._queue.gptloaded=mps._queue.gptloaded||[];mps._queue.adload=mps._queue.adload||[];mps._queue.adclone=mps._queue.adclone||[];mps._queue.adview=mps._queue.adview||[];mps._queue.refreshads=mps._queue.refreshads||[];mps.__timer=Date.now();mps.__intcode="v2";if(typeof mps.getAd!="function")mps.getAd=function(adunit){if(typeof adunit!="string")return false;var slotid="mps-getad-"+adunit.replace(/\W/g,"");if(!mps._ext||!mps._ext.loaded){mps._queue.gptloaded.push(function(){typeof mps._gptfirst=="function"&&mps._gptfirst(adunit,slotid);mps.cloneAd("#"+slotid,adunit)});mps._adsheld.push(adunit)}return'<div id="'+slotid+'" class="mps-wrapper" data-mps-fill-slot="'+adunit+'"></div>'};(function(){head=document.head||document.getElementsByTagName("head")[0],mpsload=document.createElement("script");mpsload.src="//"+mpsopts.host+"/fetch/ext/load-"+mpscall.site+".js?nowrite=2";mpsload.id="mps-load";head.insertBefore(mpsload,head.firstChild)})();

    var RottenTomatoes = RottenTomatoes || {};
    RottenTomatoes.context = { 'gptSite': "guide" };
   </script>
   <script type="text/javascript">
    var RT = RT || {};
		RT.buildHash = "898d4bef";
		RT.rtWeb = "https://www.rottentomatoes.com";
		RT.rtBridge = "https://www.rottentomatoes.com";
    RT.rtAssets = "https://editorial.rottentomatoes.com/wp-content/themes/rt-editorial";
		RT.buildCache = function(path) {
			try {
				if (!RT.buildHash) return path;

				const glue = path.includes('?') ? '&' : '?';
				return `${path}${glue}b=${RT.buildHash}`;
			} catch (err) {
				return path;
			}
		}

		var googletag = googletag || {};
		googletag.cmd = googletag.cmd || [];
		googletag.unitIds = [];
   </script>
   <meta content="max-image-preview:large" name="robots">
    <link href="//stats.wp.com" rel="dns-prefetch"/>
    <link href="//assets.adobedtm.com" rel="dns-prefetch"/>
    <link href="//ajax.googleapis.com" rel="dns-prefetch"/>
    <link href="https://editorial.rottentomatoes.com/guide/popular-movies/feed/" rel="alternate" title="Rotten Tomatoes » 30 Most Popular Movies Right Now: What to Watch In Theaters and Streaming Comments Feed" type="application/rss+xml"/>
    <link href="https://editorial.rottentomatoes.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Feditorial.rottentomatoes.com%2Fguide%2Fpopular-movies%2F" rel="alternate" title="oEmbed (JSON)" type="application/json+oembed"/>
    <link href="https://editorial.rottentomatoes.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Feditorial.rottentomatoes.com%2Fguide%2Fpopular-movies%2F&amp;format=xml" rel="alternate" title="oEmbed (XML)" type="text/xml+oembed"/>
    <style id="wp-img-auto-sizes-contain-inline-css">
     img:is([sizes=auto i],[sizes^="auto," i]){contain-intrinsic-size:3000px 1500px}
/*# sourceURL=wp-img-auto-sizes-contain-inline-css */
    </style>
    <style id="wp-emoji-styles-inline-css">
     img.wp-smiley, img.emoji {
		display: inline !important;
		border: none !important;
		box-shadow: none !important;
		height: 1em !important;
		width: 1em !important;
		margin: 0 0.07em !important;
		vertical-align: -0.1em !important;
		background: none !important;
		padding: 0 !important;
	}
/*# sourceURL=wp-emoji-styles-inline-css */
    </style>
    <style id="wp-block-library-inline-css">
     :root{--wp-block-synced-color:#7a00df;--wp-block-synced-color--rgb:122,0,223;--wp-bound-block-color:var(--wp-block-synced-color);--wp-editor-canvas-background:#ddd;--wp-admin-theme-color:#007cba;--wp-admin-theme-color--rgb:0,124,186;--wp-admin-theme-color-darker-10:#006ba1;--wp-admin-theme-color-darker-10--rgb:0,107,160.5;--wp-admin-theme-color-darker-20:#005a87;--wp-admin-theme-color-darker-20--rgb:0,90,135;--wp-admin-border-width-focus:2px}@media (min-resolution:192dpi){:root{--wp-admin-border-width-focus:1.5px}}.wp-element-button{cursor:pointer}:root .has-very-light-gray-background-color{background-color:#eee}:root .has-very-dark-gray-background-color{background-color:#313131}:root .has-very-light-gray-color{color:#eee}:root .has-very-dark-gray-color{color:#313131}:root .has-vivid-green-cyan-to-vivid-cyan-blue-gradient-background{background:linear-gradient(135deg,#00d084,#0693e3)}:root .has-purple-crush-gradient-background{background:linear-gradient(135deg,#34e2e4,#4721fb 50%,#ab1dfe)}:root .has-hazy-dawn-gradient-background{background:linear-gradient(135deg,#faaca8,#dad0ec)}:root .has-subdued-olive-gradient-background{background:linear-gradient(135deg,#fafae1,#67a671)}:root .has-atomic-cream-gradient-background{background:linear-gradient(135deg,#fdd79a,#004a59)}:root .has-nightshade-gradient-background{background:linear-gradient(135deg,#330968,#31cdcf)}:root .has-midnight-gradient-background{background:linear-gradient(135deg,#020381,#2874fc)}:root{--wp--preset--font-size--normal:16px;--wp--preset--font-size--huge:42px}.has-regular-font-size{font-size:1em}.has-larger-font-size{font-size:2.625em}.has-normal-font-size{font-size:var(--wp--preset--font-size--normal)}.has-huge-font-size{font-size:var(--wp--preset--font-size--huge)}:root .has-text-align-center{text-align:center}:root .has-text-align-left{text-align:left}:root .has-text-align-right{text-align:right}.has-fit-text{white-space:nowrap!important}#end-resizable-editor-section{display:none}.aligncenter{clear:both}.items-justified-left{justify-content:flex-start}.items-justified-center{justify-content:center}.items-justified-right{justify-content:flex-end}.items-justified-space-between{justify-content:space-between}.screen-reader-text{word-wrap:normal!important;border:0;clip-path:inset(50%);height:1px;margin:-1px;overflow:hidden;padding:0;position:absolute;width:1px}.screen-reader-text:focus{background-color:#ddd;clip-path:none;color:#444;display:block;font-size:1em;height:auto;left:5px;line-height:normal;padding:15px 23px 14px;text-decoration:none;top:5px;width:auto;z-index:100000}html :where(.has-border-color){border-style:solid}html :where([style*=border-color]){border-style:solid}html :where([style*=border-top-color]){border-top-style:solid}html :where([style*=border-right-color]){border-right-style:solid}html :where([style*=border-bottom-color]){border-bottom-style:solid}html :where([style*=border-left-color]){border-left-style:solid}html :where([style*=border-width]){border-style:solid}html :where([style*=border-top-width]){border-top-style:solid}html :where([style*=border-right-width]){border-right-style:solid}html :where([style*=border-bottom-width]){border-bottom-style:solid}html :where([style*=border-left-width]){border-left-style:solid}html :where(img[class*=wp-image-]){height:auto;max-width:100%}:where(figure){margin:0 0 1em}html :where(.is-position-sticky){--wp-admin--admin-bar--position-offset:var(--wp-admin--admin-bar--height,0px)}@media screen and (max-width:600px){html :where(.is-position-sticky){--wp-admin--admin-bar--position-offset:0px}}

/*# sourceURL=/wp-includes/css/dist/block-library/common.min.css */
    </style>
    <style id="wp-block-heading-inline-css">
     h1:where(.wp-block-heading).has-background,h2:where(.wp-block-heading).has-background,h3:where(.wp-block-heading).has-background,h4:where(.wp-block-heading).has-background,h5:where(.wp-block-heading).has-background,h6:where(.wp-block-heading).has-background{padding:1.25em 2.375em}h1.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h1.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]),h2.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h2.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]),h3.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h3.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]),h4.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h4.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]),h5.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h5.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]),h6.has-text-align-left[style*=writing-mode]:where([style*=vertical-lr]),h6.has-text-align-right[style*=writing-mode]:where([style*=vertical-rl]){rotate:180deg}
/*# sourceURL=https://editorial.rottentomatoes.com/wp-includes/blocks/heading/style.min.css */
    </style>
    <style id="wp-block-image-inline-css">

In [40]:
script = soup.findAll("div",class_= "block-countdown rkv-block")
print(len(script))

30

C:\Users\dapat\AppData\Local\Temp\ipykernel_11524\178880482.py:1: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  script = soup.findAll("div",class_= "block-countdown rkv-block")

In [44]:
list_of_movies = []
for s in script:
    df = {
        "Movie name" : s.find("a", class_="meta-title").text.strip(),
        "Rating" : s.find("span",class_="tMeterScore").text.strip()
    }
    list_of_movies.append(df)

df = pd.DataFrame(list_of_movies)
df

                                  Movie name Rating
0                                Scary Movie    24%
1                    Masters of the Universe    68%
2                                  Backrooms    88%
3                                  Obsession    94%
4                                      Hokum    90%
5                                   Pressure    86%
6       Star Wars: The Mandalorian and Grogu    62%
7                          Project Hail Mary    94%
8   The Amazing Digital Circus: The Last Act    - -
9                             Office Romance    48%
10                            Disclosure Day    81%
11                           The Breadwinner    20%
12                                   Michael    38%
13                      The Perfect Neighbor    99%
14                               In the Grey    49%
15                              Power Ballad    87%
16                                     Tuner    94%
17                                 Send Help    92%
18                                    Exit 8    93%
19                      The Sheep Detectives    95%
20                                 Iron Lung    59%
21                                   Hoppers    94%
22                              Ladies First    25%
23                               The Furious    97%
24                                 Passenger    48%
25               Remarkably Bright Creatures    84%
26                                   I Swear    97%
27                                      Apex    67%
28                           Dead Man's Wire    91%
29                                 Is God Is    97%

## pb377

In [45]:
html_doc = """
<html> <head>
<meta http-equiv="Content-Type" content="text/html;
charset=iso-8859-1">
<title>An example of HTML page</title> </head>
<body>
<h2>This is an example HTML page</h2>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at nisi velit, aliquet iaculis est. Curabitur porttitor nisi vel lacus 
euismod egestas. In hac habitasse platea dictumst. In sagittis magna eu odio interdum mollis. Phasellus sagittis pulvinar facilisis. 
Donec vel odio volutpat tortor volutpat commodo. Donec vehicula vulputate sem, vel iaculis urna molestie eget. Sed 
pellentesque adipiscing tortor, at condimentum elit elementum sed. Mauris dignissim
elementum nunc, non elementum felis condimentum eu. In in turpis quis erat imperdiet vulputate. Pellentesque mauris turpis, 
dignissim sed iaculis eu, euismod eget ipsum. Vivamus mollis adipiscing viverra. Morbi at sem eget nisl euismod porta.</p>
<p><a href="https://www.w3resource.com/html/HTML-tutorials.php">Learn HTML from
w3resource.com</a></p>
<p><a href="https://www.w3resource.com/css/CSS-tutorials.php">Learn CSS from 
w3resource.com</a></p>
</body>
</html>
"""

In [46]:
soup = bs4.BeautifulSoup(html_doc, "html.parser")
print(soup.prettify())

<html>
 <head>
  <meta content="text/html;
charset=utf-8" http-equiv="Content-Type"/>
  <title>
   An example of HTML page
  </title>
 </head>
 <body>
  <h2>
   This is an example HTML page
  </h2>
  <p>
   Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at nisi velit, aliquet iaculis est. Curabitur porttitor nisi vel lacus
euismod egestas. In hac habitasse platea dictumst. In sagittis magna eu odio interdum mollis. Phasellus sagittis pulvinar facilisis.
Donec vel odio volutpat tortor volutpat commodo. Donec vehicula vulputate sem, vel iaculis urna molestie eget. Sed
pellentesque adipiscing tortor, at condimentum elit elementum sed. Mauris dignissim
elementum nunc, non elementum felis condimentum eu. In in turpis quis erat imperdiet vulputate. Pellentesque mauris turpis,
dignissim sed iaculis eu, euismod eget ipsum. Vivamus mollis adipiscing viverra. Morbi at sem eget nisl euismod porta.
  </p>
  <p>
   <a href="https://www.w3resource.com/html/HTML-tutorials.php">
    Learn HTML from
w3resource.com
   </a>
  </p>
  <p>
   <a href="https://www.w3resource.com/css/CSS-tutorials.php">
    Learn CSS from
w3resource.com
   </a>
  </p>
 </body>
</html>

In [47]:
print(soup.find("title").text)

An example of HTML page

## pb383  Write a Python program to interact with the following REST API:The program should: Send a POST request to create a new user. Send JSON data containing name and job. Include a custom Authorization header token. Convert the API response to a Python dictionary(JSON).
https://reqres.in/api/users

In [49]:
url="https://reqres.in/api/users"
userdata = {
    "name": "Dhairya",
    "job": "Student"
}
headers = {
    "Content-Type": "application/json",
    "Authorization" : "free_user_3FDELW234t94kT1LLCR02BquP69"
}
response = requests.post(url, json=userdata, headers=headers)
data = response.json()

print("Response code : ",response.status_code)
print("Response data : ",data)
print("Name] : ",data.get("name"))
print("Job : ",data.get("job"))

Response code :  401
Response data :  {'error': 'missing_api_key', 'message': 'The x-api-key header is required for this endpoint.', 'hint': 'Create a free key at app.reqres.in and send it as x-api-key.', 'next_steps': ['Go to app.reqres.in/api-keys to get your key', 'Add header: x-api-key: <your_key>', 'For app user endpoints, use Authorization: Bearer <session_token> instead'], 'docs_url': 'https://app.reqres.in/docs#authentication', 'example_curl': 'curl -H "x-api-key: YOUR_API_KEY" https://api.reqres.in/api/collections', '_meta': {'powered_by': 'ReqRes', 'docs_url': 'https://app.reqres.in/documentation', 'upgrade_url': 'https://app.reqres.in/upgrade', 'example_url': 'https://app.reqres.in/examples/notes-app', 'variant': 'v1_a', 'message': 'API key invalid or revoked. Create a new key in API Keys.', 'cta': {'label': 'Get a key', 'url': 'https://app.reqres.in/api-keys'}, 'context': 'invalid_key'}}
Name] :  None
Job :  None