In [1]:
api_key = "pgOoL9bZd7fECCM4vgxpUwah5BxyGQJU0WoNKW0a"

In [2]:
import requests
url = "https://api.nasa.gov/planetary/apod?api_key="+api_key
response = requests.get(url)
print(response)

<Response [200]>

In [3]:
data = response.json()
print(data)

{'date': '2026-05-29', 'explanation': "A gorgeous spiral galaxy, Messier 104 is famous for its nearly edge-on profile featuring a broad ring of obscuring dust lanes. Seen in silhouette against an extensive central bulge of stars, the swath of cosmic dust lends a broad brimmed hat-like appearance to the galaxy suggesting a more popular moniker, the Sombrero Galaxy. Also known as NGC 4594, the Sombrero galaxy can be seen across the spectrum and is host to a central supermassive black hole. About 50,000 light-years across and 28 million light-years away, M104 is one of the largest galaxies at the southern edge of the Virgo Galaxy Cluster. Still, the spiky foreground stars in this field of view lie well within our own Milky Way. This broad view of the well-known galaxy was processed to reveal M104's extended halo, as well as a faint tidal stellar stream. It was captured by the Dark Energy Camera (DECam) on the Blanco 4-meter telescope at the Cerro Tololo Inter-American Observatory.", 'hdurl': 'https://apod.nasa.gov/apod/image/2605/M104noirlab2612a.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Messier 104', 'url': 'https://apod.nasa.gov/apod/image/2605/M104noirlab2612a_1024.jpg'}

In [4]:
import json
print(json.dumps(data, indent=5))

{
     "date": "2026-05-29",
     "explanation": "A gorgeous spiral galaxy, Messier 104 is famous for its nearly edge-on profile featuring a broad ring of obscuring dust lanes. Seen in silhouette against an extensive central bulge of stars, the swath of cosmic dust lends a broad brimmed hat-like appearance to the galaxy suggesting a more popular moniker, the Sombrero Galaxy. Also known as NGC 4594, the Sombrero galaxy can be seen across the spectrum and is host to a central supermassive black hole. About 50,000 light-years across and 28 million light-years away, M104 is one of the largest galaxies at the southern edge of the Virgo Galaxy Cluster. Still, the spiky foreground stars in this field of view lie well within our own Milky Way. This broad view of the well-known galaxy was processed to reveal M104's extended halo, as well as a faint tidal stellar stream. It was captured by the Dark Energy Camera (DECam) on the Blanco 4-meter telescope at the Cerro Tololo Inter-American Observatory.",
     "hdurl": "https://apod.nasa.gov/apod/image/2605/M104noirlab2612a.jpg",
     "media_type": "image",
     "service_version": "v1",
     "title": "Messier 104",
     "url": "https://apod.nasa.gov/apod/image/2605/M104noirlab2612a_1024.jpg"
}

In [5]:
print(data['hdurl'])

https://apod.nasa.gov/apod/image/2605/M104noirlab2612a.jpg

In [6]:
print(data['explanation'])

A gorgeous spiral galaxy, Messier 104 is famous for its nearly edge-on profile featuring a broad ring of obscuring dust lanes. Seen in silhouette against an extensive central bulge of stars, the swath of cosmic dust lends a broad brimmed hat-like appearance to the galaxy suggesting a more popular moniker, the Sombrero Galaxy. Also known as NGC 4594, the Sombrero galaxy can be seen across the spectrum and is host to a central supermassive black hole. About 50,000 light-years across and 28 million light-years away, M104 is one of the largest galaxies at the southern edge of the Virgo Galaxy Cluster. Still, the spiky foreground stars in this field of view lie well within our own Milky Way. This broad view of the well-known galaxy was processed to reveal M104's extended halo, as well as a faint tidal stellar stream. It was captured by the Dark Energy Camera (DECam) on the Blanco 4-meter telescope at the Cerro Tololo Inter-American Observatory.

In [7]:
import requests
url = "https://api.nasa.gov/planetary/apod?api_key="+api_key
response = requests.get(url, params={'count':10})
data = response.json()
print(data)

[{'copyright': 'Tunc Tezel', 'date': '2019-05-04', 'explanation': "On February 2nd early morning risers saw Saturn near an old Moon low on the eastern horizon. On that date bright planet, sunlit crescent, and faint lunar night side were captured in this predawn skyscape from Bursa, Turkey. Of course the Moon's ashen glow is earthshine, earthlight reflected from the Moon's night side. A description of earthshine, in terms of sunlight reflected by Earth's oceans illuminating the Moon's dark surface, was written over 500 years ago by Leonardo da Vinci. On May 2nd an old Moon also rose in the predawn twilight. On that date its ashen glow shared the sky with Venus, the brilliant morning star. May 2nd also marked the 500th anniversary of Leonardo's death in 1519.", 'hdurl': 'https://apod.nasa.gov/apod/image/1905/20190202tezel.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Saturn and the Da Vinci Glow', 'url': 'https://apod.nasa.gov/apod/image/1905/20190202tezel_1024.jpg'}, {'date': '2002-06-17', 'explanation': "The many bright, point-like sources in this Chandra Observatory x-ray image lie within NGC 4697, an elliptical galaxy some 40 million light-years away towards Virgo. Like other normal elliptical galaxies, NGC 4697 is a spherical ensemble of mainly older, fainter, low mass stars, with little star forming gas and dust compared to spiral galaxies. But the luminous x-ray sources in the Chandra image indicate that NGC 4697 had a wilder youth. Powering the x-ray sources are neutron stars and black holes in binary star systems, where x-rays are generated as matter from a more ordinary companion star falls in to these bizarre, compact objects. Since neutron stars and black holes are the endpoints in the lives of massive stars, NGC 4697 must have had many bright, massive stars in its past. An exceptionally large number of NGC 4697's x-ray binaries are found in the galaxy's globular star clusters, suggesting that dense star clusters are a good place for neutron stars and black holes to capture a companion. Stellar winds and supernovae explosions of massive stars could also have produced the hot gas responsible for this galaxy's diffuse x-ray glow.", 'hdurl': 'https://apod.nasa.gov/apod/image/0206/ngc4697_cxc.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'NGC 4697: X-Rays from an Elliptical Galaxy', 'url': 'https://apod.nasa.gov/apod/image/0206/ngc4697_cxc_c1.jpg'}, {'copyright': 'Mark Hersch', 'date': '2020-06-24', 'explanation': "How could that city be upside-down? The city, Chicago, was actually perfectly right-side up. The long shadows it projected onto nearby Lake Michigan near sunset, however, when seen in reflection, made the buildings appear inverted. This fascinating, puzzling, yet beautiful image was captured by a photographer in 2014 on an airplane on approach to Chicago's O'Hare International Airport.  The Sun can be seen both above and below the cloud deck, with the latter reflected in the calm lake.  As a bonus, if you look really closely -- and this is quite a challenge -- you can find another airplane in the image, likely also on approach to the same airport.", 'hdurl': 'https://apod.nasa.gov/apod/image/2006/ChicagoClouds_Hersch_3600.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Inverted City Beneath Clouds', 'url': 'https://apod.nasa.gov/apod/image/2006/ChicagoClouds_Hersch_960.jpg'}, {'copyright': 'Stefan Seip', 'date': '2009-10-22', 'explanation': 'Last Friday, a gathering of three bright planets and the Moon graced the morning sky. With Mercury, Venus, Saturn, and a narrow lunar crescent close to the eastern horizon in the dawn twilight, this picture of the beautiful conjunction was recorded near Noerdlingen, Germany. These planets are wandering apart now and Mercury is sinking closer toward the rising Sun. But if you also scan the rest of the sky this week you should be able to add Jupiter and Mars to your planet spotting list, as Mars rises around midnight and Jupiter shines brightly after sunset. In fact, if you want a better view of Jupiter than Galileo had, you might check out the 2009 International Year of Astronomy activities and events during these next few Galilean Nights (October 22-24).', 'hdurl': 'https://apod.nasa.gov/apod/image/0910/3PlanetsMoon_seip.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Moon and Planets in the Morning', 'url': 'https://apod.nasa.gov/apod/image/0910/3PlanetsMoonLabel_seip900.jpg'}, {'date': '2004-11-06', 'explanation': 'Using the orbiting Chandra X-ray Observatory, astronomers have taken this long look at the core of our Milky Way galaxy, some 26,000 light-years away. The spectacular false-color view spans about 130 light-years. It reveals an energetic region rich in x-ray sources and high-lighted by the central source, Sagittarius A*, known to be a supermassive black hole with 3 million times the mass of the Sun. Given its tremendous mass, Sagittarius A* is amazingly faint in x-rays in comparison to central black holes observed in distant galaxies, even during its frequent x-ray flares. This suggests that this supermassive black hole has been starved by a lack of infalling material. In fact, the sharp Chandra image shows clouds of multi-million degree gas dozens of light-years across flanking (upper right and lower left) the central region -- evidence that violent events have cleared much material from the vicinity of the black hole.', 'hdurl': 'https://apod.nasa.gov/apod/image/0411/mwcore_cxo_full.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'X-Rays from the Galactic Core', 'url': 'https://apod.nasa.gov/apod/image/0411/mwcore_cxo_c1.jpg'}, {'date': '2008-10-19', 'explanation': 'The center of the Lagoon Nebula is a whirlwind of spectacular star formation. Visible on the upper left, at least two long funnel-shaped clouds, each roughly half a light-year long, have been formed by extreme stellar winds and intense energetic starlight.  The tremendously bright nearby star, Hershel 36, lights the area.  Vast walls of dust hide and redden other hot young stars.  As energy from these stars pours into the cool dust and gas, large temperature differences in adjoining regions can be created generating shearing winds which may cause the funnels.  This picture, spanning about 5 light years, was taken in 1995 by the orbiting Hubble Space Telescope.  The Lagoon Nebula, also known as M8, lies about 5000 light years distant toward the constellation of Sagittarius.', 'hdurl': 'https://apod.nasa.gov/apod/image/0810/lagoon_hst_big.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'In the Center of the Lagoon Nebula', 'url': 'https://apod.nasa.gov/apod/image/0810/lagoon_hst.jpg'}, {'copyright': 'Philip Perkins', 'date': '2002-05-09', 'explanation': "Stonehenge, four thousand year old monument to the Sun, provides an appropriate setting for this delightful snapshot of the Sun's children gathering in planet Earth's sky. While the massive stone structure dates from around 2000 B.C., this arrangement of the visible planets was recorded only a few days ago on the evening of May 4th, 2002 A.D. Bright Jupiter stands highest above the horizon at the upper left. A remarkable, almost equilateral triangle formed by Saturn (left), Mars (top), and Venus (right) is placed just above the stones near picture center. Fighting the glow of the setting sun, Mercury can be spotted closest to the horizon, below and right of the planetary triad. Still easy to enjoy for casual sky gazers, this photogenic and slowly shifting planetary grouping will be joined by a young crescent Moon beginning Monday, May 13.", 'hdurl': 'https://apod.nasa.gov/apod/image/0205/planets1stonehenge_perkins_big.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Planets Over Stonehenge', 'url': 'https://apod.nasa.gov/apod/image/0205/planets1stonehenge_perkins.jpg'}, {'copyright': 'Bob Franke', 'date': '2014-02-22', 'explanation': "A mere 600 light-years away, M44 is one of the closest star clusters to our solar system. Also known as the Praesepe or the Beehive cluster its stars are young though, about 600 million years old compared to our Sun's 4.5 billion years. Based on similar ages and motion through space, M44 and the even closer Hyades star cluster in Taurus are thought to have been born together in the same large molecular cloud. An open cluster spanning some 15 light-years, M44 holds 1,000 stars or so and covers about 3 full moons (1.5 degrees) on the sky in the constellation Cancer. Visible to the unaided eye, M44 has been recognized since antiquity. Described as a faint cloud or celestial mist long before being included as the 44th entry in Charles Messier's 18th century catalog, the cluster was not resolved into its individual stars until telescopes were available. A popular target for modern, binocular-equiped sky gazers, the cluster's few yellowish tinted, cool, red giants are scattered through the field of its brighter hot blue main sequence stars in this colorful stellar group snapshot.", 'hdurl': 'https://apod.nasa.gov/apod/image/1402/m44franke1600.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'M44: The Beehive Cluster', 'url': 'https://apod.nasa.gov/apod/image/1402/m44franke900.jpg'}, {'date': '2008-10-12', 'explanation': "Is this what our own Milky Way Galaxy looks like from far away? Similar in size and grand design to our home Galaxy (although without the central bar), spiral galaxy NGC 3370 lies about 100 million light-years away toward the constellation of the Lion (Leo).  Recorded above in exquisite detail by the Hubble Space Telescope's Advanced Camera for Surveys, the big, beautiful face-on spiral is not only photogenic, but has proven sharp enough to study individual stars known as Cepheids. These pulsating stars have been used to accurately determine NGC 3370's distance. NGC 3370 was chosen for this study because in 1994 the spiral galaxy was also home to a well studied stellar explosion -- a Type Ia supernova.  Combining the known distance to this standard candle supernova, based on the Cepheid measurements, with observations of supernovas at even greater distances, has helped to reveal the size and expansion rate of the entire Universe itself.", 'hdurl': 'https://apod.nasa.gov/apod/image/0810/ngc3370_hst_big.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Spiral Galaxy NGC 3370 from Hubble', 'url': 'https://apod.nasa.gov/apod/image/0810/ngc3370_hst.jpg'}, {'copyright': 'Dzmitry Kananovich', 'date': '2020-06-21', 'explanation': "It may look like Earthrise, but it's actually Venus-set. Just after sunrise two days ago, both the Moon and Venus also rose.  But then the Moon overtook Venus. In the featured image sequence centered on the Moon, Venus is shown increasingly angularly close to the Moon. In the famous Earthrise image taken just over 50 years ago, the Earth was captured rising over the edge of the Moon, as seen from the Apollo 8 crew orbiting the Moon. This similar Venus-set image was taken from Earth, of course, specifically Estonia.  Venus shows only a thin crescent because last week it passed nearly in front of the Sun, as seen from Earth.  The Moon shows only a thin crescent because it will soon be passing directly in front of the Sun, as seen from Earth. Today, in fact, two days after this image was taken, the Moon will create a solar eclipse, with a thin swath across the Earth treated to an annular solar eclipse.    Gallery: Notable images of the Venus - Mooon conjunction of 2020 June submitted to APOD", 'hdurl': 'https://apod.nasa.gov/apod/image/2006/VenusSet_Kananovich_1000.jpg', 'media_type': 'image', 'service_version': 'v1', 'title': 'Moon Occults Venus', 'url': 'https://apod.nasa.gov/apod/image/2006/VenusSet_Kananovich_1000.jpg'}]

In [8]:
print(json.dumps(data, indent=5))

[
     {
          "copyright": "Tunc Tezel",
          "date": "2019-05-04",
          "explanation": "On February 2nd early morning risers saw Saturn near an old Moon low on the eastern horizon. On that date bright planet, sunlit crescent, and faint lunar night side were captured in this predawn skyscape from Bursa, Turkey. Of course the Moon's ashen glow is earthshine, earthlight reflected from the Moon's night side. A description of earthshine, in terms of sunlight reflected by Earth's oceans illuminating the Moon's dark surface, was written over 500 years ago by Leonardo da Vinci. On May 2nd an old Moon also rose in the predawn twilight. On that date its ashen glow shared the sky with Venus, the brilliant morning star. May 2nd also marked the 500th anniversary of Leonardo's death in 1519.",
          "hdurl": "https://apod.nasa.gov/apod/image/1905/20190202tezel.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "Saturn and the Da Vinci Glow",
          "url": "https://apod.nasa.gov/apod/image/1905/20190202tezel_1024.jpg"
     },
     {
          "date": "2002-06-17",
          "explanation": "The many bright, point-like sources in this Chandra Observatory x-ray image lie within NGC 4697, an elliptical galaxy some 40 million light-years away towards Virgo. Like other normal elliptical galaxies, NGC 4697 is a spherical ensemble of mainly older, fainter, low mass stars, with little star forming gas and dust compared to spiral galaxies. But the luminous x-ray sources in the Chandra image indicate that NGC 4697 had a wilder youth. Powering the x-ray sources are neutron stars and black holes in binary star systems, where x-rays are generated as matter from a more ordinary companion star falls in to these bizarre, compact objects. Since neutron stars and black holes are the endpoints in the lives of massive stars, NGC 4697 must have had many bright, massive stars in its past. An exceptionally large number of NGC 4697's x-ray binaries are found in the galaxy's globular star clusters, suggesting that dense star clusters are a good place for neutron stars and black holes to capture a companion. Stellar winds and supernovae explosions of massive stars could also have produced the hot gas responsible for this galaxy's diffuse x-ray glow.",
          "hdurl": "https://apod.nasa.gov/apod/image/0206/ngc4697_cxc.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "NGC 4697: X-Rays from an Elliptical Galaxy",
          "url": "https://apod.nasa.gov/apod/image/0206/ngc4697_cxc_c1.jpg"
     },
     {
          "copyright": "Mark Hersch",
          "date": "2020-06-24",
          "explanation": "How could that city be upside-down? The city, Chicago, was actually perfectly right-side up. The long shadows it projected onto nearby Lake Michigan near sunset, however, when seen in reflection, made the buildings appear inverted. This fascinating, puzzling, yet beautiful image was captured by a photographer in 2014 on an airplane on approach to Chicago's O'Hare International Airport.  The Sun can be seen both above and below the cloud deck, with the latter reflected in the calm lake.  As a bonus, if you look really closely -- and this is quite a challenge -- you can find another airplane in the image, likely also on approach to the same airport.",
          "hdurl": "https://apod.nasa.gov/apod/image/2006/ChicagoClouds_Hersch_3600.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "Inverted City Beneath Clouds",
          "url": "https://apod.nasa.gov/apod/image/2006/ChicagoClouds_Hersch_960.jpg"
     },
     {
          "copyright": "Stefan Seip",
          "date": "2009-10-22",
          "explanation": "Last Friday, a gathering of three bright planets and the Moon graced the morning sky. With Mercury, Venus, Saturn, and a narrow lunar crescent close to the eastern horizon in the dawn twilight, this picture of the beautiful conjunction was recorded near Noerdlingen, Germany. These planets are wandering apart now and Mercury is sinking closer toward the rising Sun. But if you also scan the rest of the sky this week you should be able to add Jupiter and Mars to your planet spotting list, as Mars rises around midnight and Jupiter shines brightly after sunset. In fact, if you want a better view of Jupiter than Galileo had, you might check out the 2009 International Year of Astronomy activities and events during these next few Galilean Nights (October 22-24).",
          "hdurl": "https://apod.nasa.gov/apod/image/0910/3PlanetsMoon_seip.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "Moon and Planets in the Morning",
          "url": "https://apod.nasa.gov/apod/image/0910/3PlanetsMoonLabel_seip900.jpg"
     },
     {
          "date": "2004-11-06",
          "explanation": "Using the orbiting Chandra X-ray Observatory, astronomers have taken this long look at the core of our Milky Way galaxy, some 26,000 light-years away. The spectacular false-color view spans about 130 light-years. It reveals an energetic region rich in x-ray sources and high-lighted by the central source, Sagittarius A*, known to be a supermassive black hole with 3 million times the mass of the Sun. Given its tremendous mass, Sagittarius A* is amazingly faint in x-rays in comparison to central black holes observed in distant galaxies, even during its frequent x-ray flares. This suggests that this supermassive black hole has been starved by a lack of infalling material. In fact, the sharp Chandra image shows clouds of multi-million degree gas dozens of light-years across flanking (upper right and lower left) the central region -- evidence that violent events have cleared much material from the vicinity of the black hole.",
          "hdurl": "https://apod.nasa.gov/apod/image/0411/mwcore_cxo_full.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "X-Rays from the Galactic Core",
          "url": "https://apod.nasa.gov/apod/image/0411/mwcore_cxo_c1.jpg"
     },
     {
          "date": "2008-10-19",
          "explanation": "The center of the Lagoon Nebula is a whirlwind of spectacular star formation. Visible on the upper left, at least two long funnel-shaped clouds, each roughly half a light-year long, have been formed by extreme stellar winds and intense energetic starlight.  The tremendously bright nearby star, Hershel 36, lights the area.  Vast walls of dust hide and redden other hot young stars.  As energy from these stars pours into the cool dust and gas, large temperature differences in adjoining regions can be created generating shearing winds which may cause the funnels.  This picture, spanning about 5 light years, was taken in 1995 by the orbiting Hubble Space Telescope.  The Lagoon Nebula, also known as M8, lies about 5000 light years distant toward the constellation of Sagittarius.",
          "hdurl": "https://apod.nasa.gov/apod/image/0810/lagoon_hst_big.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "In the Center of the Lagoon Nebula",
          "url": "https://apod.nasa.gov/apod/image/0810/lagoon_hst.jpg"
     },
     {
          "copyright": "Philip Perkins",
          "date": "2002-05-09",
          "explanation": "Stonehenge, four thousand year old monument to the Sun, provides an appropriate setting for this delightful snapshot of the Sun's children gathering in planet Earth's sky. While the massive stone structure dates from around 2000 B.C., this arrangement of the visible planets was recorded only a few days ago on the evening of May 4th, 2002 A.D. Bright Jupiter stands highest above the horizon at the upper left. A remarkable, almost equilateral triangle formed by Saturn (left), Mars (top), and Venus (right) is placed just above the stones near picture center. Fighting the glow of the setting sun, Mercury can be spotted closest to the horizon, below and right of the planetary triad. Still easy to enjoy for casual sky gazers, this photogenic and slowly shifting planetary grouping will be joined by a young crescent Moon beginning Monday, May 13.",
          "hdurl": "https://apod.nasa.gov/apod/image/0205/planets1stonehenge_perkins_big.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "Planets Over Stonehenge",
          "url": "https://apod.nasa.gov/apod/image/0205/planets1stonehenge_perkins.jpg"
     },
     {
          "copyright": "Bob Franke",
          "date": "2014-02-22",
          "explanation": "A mere 600 light-years away, M44 is one of the closest star clusters to our solar system. Also known as the Praesepe or the Beehive cluster its stars are young though, about 600 million years old compared to our Sun's 4.5 billion years. Based on similar ages and motion through space, M44 and the even closer Hyades star cluster in Taurus are thought to have been born together in the same large molecular cloud. An open cluster spanning some 15 light-years, M44 holds 1,000 stars or so and covers about 3 full moons (1.5 degrees) on the sky in the constellation Cancer. Visible to the unaided eye, M44 has been recognized since antiquity. Described as a faint cloud or celestial mist long before being included as the 44th entry in Charles Messier's 18th century catalog, the cluster was not resolved into its individual stars until telescopes were available. A popular target for modern, binocular-equiped sky gazers, the cluster's few yellowish tinted, cool, red giants are scattered through the field of its brighter hot blue main sequence stars in this colorful stellar group snapshot.",
          "hdurl": "https://apod.nasa.gov/apod/image/1402/m44franke1600.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "M44: The Beehive Cluster",
          "url": "https://apod.nasa.gov/apod/image/1402/m44franke900.jpg"
     },
     {
          "date": "2008-10-12",
          "explanation": "Is this what our own Milky Way Galaxy looks like from far away? Similar in size and grand design to our home Galaxy (although without the central bar), spiral galaxy NGC 3370 lies about 100 million light-years away toward the constellation of the Lion (Leo).  Recorded above in exquisite detail by the Hubble Space Telescope's Advanced Camera for Surveys, the big, beautiful face-on spiral is not only photogenic, but has proven sharp enough to study individual stars known as Cepheids. These pulsating stars have been used to accurately determine NGC 3370's distance. NGC 3370 was chosen for this study because in 1994 the spiral galaxy was also home to a well studied stellar explosion -- a Type Ia supernova.  Combining the known distance to this standard candle supernova, based on the Cepheid measurements, with observations of supernovas at even greater distances, has helped to reveal the size and expansion rate of the entire Universe itself.",
          "hdurl": "https://apod.nasa.gov/apod/image/0810/ngc3370_hst_big.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "Spiral Galaxy NGC 3370 from Hubble",
          "url": "https://apod.nasa.gov/apod/image/0810/ngc3370_hst.jpg"
     },
     {
          "copyright": "Dzmitry Kananovich",
          "date": "2020-06-21",
          "explanation": "It may look like Earthrise, but it's actually Venus-set. Just after sunrise two days ago, both the Moon and Venus also rose.  But then the Moon overtook Venus. In the featured image sequence centered on the Moon, Venus is shown increasingly angularly close to the Moon. In the famous Earthrise image taken just over 50 years ago, the Earth was captured rising over the edge of the Moon, as seen from the Apollo 8 crew orbiting the Moon. This similar Venus-set image was taken from Earth, of course, specifically Estonia.  Venus shows only a thin crescent because last week it passed nearly in front of the Sun, as seen from Earth.  The Moon shows only a thin crescent because it will soon be passing directly in front of the Sun, as seen from Earth. Today, in fact, two days after this image was taken, the Moon will create a solar eclipse, with a thin swath across the Earth treated to an annular solar eclipse.    Gallery: Notable images of the Venus - Mooon conjunction of 2020 June submitted to APOD",
          "hdurl": "https://apod.nasa.gov/apod/image/2006/VenusSet_Kananovich_1000.jpg",
          "media_type": "image",
          "service_version": "v1",
          "title": "Moon Occults Venus",
          "url": "https://apod.nasa.gov/apod/image/2006/VenusSet_Kananovich_1000.jpg"
     }
]

In [9]:
name = []
url = []
explanation = []
for i in data:
    name.append(i['title'])
    url.append(i['url'])
    explanation.append(i['explanation'])

In [10]:
import pandas as pd
df = pd.DataFrame({
    'name':name,
    'url':url,
    'explanation':explanation
})

In [11]:
df

,name,url,explanation
0,Saturn and the Da Vinci Glow,https://apod.nasa.gov/apod/image/1905/20190202...,On February 2nd early morning risers saw Satur...
1,NGC 4697: X-Rays from an Elliptical Galaxy,https://apod.nasa.gov/apod/image/0206/ngc4697_...,"The many bright, point-like sources in this Ch..."
2,Inverted City Beneath Clouds,https://apod.nasa.gov/apod/image/2006/ChicagoC...,"How could that city be upside-down? The city, ..."
3,Moon and Planets in the Morning,https://apod.nasa.gov/apod/image/0910/3Planets...,"Last Friday, a gathering of three bright plane..."
4,X-Rays from the Galactic Core,https://apod.nasa.gov/apod/image/0411/mwcore_c...,"Using the orbiting Chandra X-ray Observatory, ..."
5,In the Center of the Lagoon Nebula,https://apod.nasa.gov/apod/image/0810/lagoon_h...,The center of the Lagoon Nebula is a whirlwind...
6,Planets Over Stonehenge,https://apod.nasa.gov/apod/image/0205/planets1...,"Stonehenge, four thousand year old monument to..."
7,M44: The Beehive Cluster,https://apod.nasa.gov/apod/image/1402/m44frank...,"A mere 600 light-years away, M44 is one of the..."
8,Spiral Galaxy NGC 3370 from Hubble,https://apod.nasa.gov/apod/image/0810/ngc3370_...,Is this what our own Milky Way Galaxy looks li...
9,Moon Occults Venus,https://apod.nasa.gov/apod/image/2006/VenusSet...,"It may look like Earthrise, but it's actually ..."

In [12]:
api_key = '3beddd7f21592afe5787c62211bca984'
url = "http://api.openweathermap.org/geo/1.0/direct?q=Ahmedabad&limit=5&appid="+api_key
response = requests.get(url)
print(response)

<Response [200]>

In [13]:
data = response.json()
print(data)

[{'name': 'Ahmedabad', 'local_names': {'ru': 'Ахмадабад', 'uk': 'Ахмедабад', 'or': 'ଅହମଦାବାଦ', 'ta': 'அகமதாபாத்', 'bn': 'আহমেদাবাদ', 'hi': 'अहमदाबाद', 'ur': 'احمد آباد', 'de': 'Ahmedabad', 'feature_name': 'Ahmedabad', 'pa': 'ਅਹਿਮਦਾਬਾਦ', 'zh': '艾哈迈达巴德', 'pl': 'Ahmadabad', 'eo': 'Ahmadabado', 'gu': 'અમદાવાદ', 'kn': 'ಅಹ್ಮದಾಬಾದ್', 'ml': 'അഹമ്മദാബാദ്', 'oc': 'Ahmadabad', 'cs': 'Ahmadábád', 'he': 'אחמדאבאד', 'ascii': 'Ahmedabad', 'ne': 'अहमदाबाद', 'ja': 'アフマダーバード', 'tt': 'Әхмәтабад', 'ar': 'أحمد آباد', 'mr': 'अहमदाबाद', 'en': 'Ahmedabad', 'te': 'అహ్మదాబాద్'}, 'lat': 23.0215374, 'lon': 72.5800568, 'country': 'IN', 'state': 'Gujarat'}, {'name': 'Ahmedabad', 'local_names': {'en': 'Ahmedabad'}, 'lat': 32.5022729, 'lon': 72.8536319, 'country': 'PK', 'state': 'Punjab'}, {'name': 'Ahmedabad', 'local_names': {'en': 'Ahmedabad'}, 'lat': 24.7312039, 'lon': 67.6891818, 'country': 'PK', 'state': 'Sindh'}, {'name': 'Ahmedabad', 'lat': 32.9649355, 'lon': 74.2725539, 'country': 'PK', 'state': 'Azad Kashmir'}, {'name': 'Ahmedabad', 'local_names': {'en': 'Ahmedabad'}, 'lat': 31.4963792, 'lon': 72.0759963, 'country': 'PK', 'state': 'Punjab'}]

In [14]:
print(json.dumps(data, indent=5))

[
     {
          "name": "Ahmedabad",
          "local_names": {
               "ru": "\u0410\u0445\u043c\u0430\u0434\u0430\u0431\u0430\u0434",
               "uk": "\u0410\u0445\u043c\u0435\u0434\u0430\u0431\u0430\u0434",
               "or": "\u0b05\u0b39\u0b2e\u0b26\u0b3e\u0b2c\u0b3e\u0b26",
               "ta": "\u0b85\u0b95\u0bae\u0ba4\u0bbe\u0baa\u0bbe\u0ba4\u0bcd",
               "bn": "\u0986\u09b9\u09ae\u09c7\u09a6\u09be\u09ac\u09be\u09a6",
               "hi": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "ur": "\u0627\u062d\u0645\u062f \u0622\u0628\u0627\u062f",
               "de": "Ahmedabad",
               "feature_name": "Ahmedabad",
               "pa": "\u0a05\u0a39\u0a3f\u0a2e\u0a26\u0a3e\u0a2c\u0a3e\u0a26",
               "zh": "\u827e\u54c8\u8fc8\u8fbe\u5df4\u5fb7",
               "pl": "Ahmadabad",
               "eo": "Ahmadabado",
               "gu": "\u0a85\u0aae\u0aa6\u0abe\u0ab5\u0abe\u0aa6",
               "kn": "\u0c85\u0cb9\u0ccd\u0cae\u0ca6\u0cbe\u0cac\u0cbe\u0ca6\u0ccd",
               "ml": "\u0d05\u0d39\u0d2e\u0d4d\u0d2e\u0d26\u0d3e\u0d2c\u0d3e\u0d26\u0d4d",
               "oc": "Ahmadabad",
               "cs": "Ahmad\u00e1b\u00e1d",
               "he": "\u05d0\u05d7\u05de\u05d3\u05d0\u05d1\u05d0\u05d3",
               "ascii": "Ahmedabad",
               "ne": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "ja": "\u30a2\u30d5\u30de\u30c0\u30fc\u30d0\u30fc\u30c9",
               "tt": "\u04d8\u0445\u043c\u04d9\u0442\u0430\u0431\u0430\u0434",
               "ar": "\u0623\u062d\u0645\u062f \u0622\u0628\u0627\u062f",
               "mr": "\u0905\u0939\u092e\u0926\u093e\u092c\u093e\u0926",
               "en": "Ahmedabad",
               "te": "\u0c05\u0c39\u0c4d\u0c2e\u0c26\u0c3e\u0c2c\u0c3e\u0c26\u0c4d"
          },
          "lat": 23.0215374,
          "lon": 72.5800568,
          "country": "IN",
          "state": "Gujarat"
     },
     {
          "name": "Ahmedabad",
          "local_names": {
               "en": "Ahmedabad"
          },
          "lat": 32.5022729,
          "lon": 72.8536319,
          "country": "PK",
          "state": "Punjab"
     },
     {
          "name": "Ahmedabad",
          "local_names": {
               "en": "Ahmedabad"
          },
          "lat": 24.7312039,
          "lon": 67.6891818,
          "country": "PK",
          "state": "Sindh"
     },
     {
          "name": "Ahmedabad",
          "lat": 32.9649355,
          "lon": 74.2725539,
          "country": "PK",
          "state": "Azad Kashmir"
     },
     {
          "name": "Ahmedabad",
          "local_names": {
               "en": "Ahmedabad"
          },
          "lat": 31.4963792,
          "lon": 72.0759963,
          "country": "PK",
          "state": "Punjab"
     }
]

In [15]:
lat = data[0]['lat']
lon = data[0]['lon']
print(lat)
print(lon)

23.0215374
72.5800568

In [16]:
url = f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}.99&appid={api_key}&units=metric"
response = requests.get(url)
print(url)
response = requests.get(url)
print(response)

https://api.openweathermap.org/data/2.5/weather?lat=23.0215374&lon=72.5800568.99&appid=3beddd7f21592afe5787c62211bca984&units=metric
<Response [400]>

In [17]:
data = response.json()
print(data)

{'cod': '400', 'message': 'wrong longitude'}

In [18]:
url = f"http://api.openweathermap.org/data/2.5/air_pollution?lat={lat}&lon={lon}&appid={api_key}&units=metric"
response = requests.get(url)
print(response)

<Response [200]>

In [19]:
data=response.json()
print(data)

{'coord': {'lon': 72.5801, 'lat': 23.0215}, 'list': [{'main': {'aqi': 2}, 'components': {'co': 95.91, 'no': 0.17, 'no2': 0.79, 'o3': 62.61, 'so2': 1.36, 'pm2_5': 7.8, 'pm10': 32.03, 'nh3': 0.62}, 'dt': 1780035001}]}

In [20]:
print(json.dumps(data, indent=5))

{
     "coord": {
          "lon": 72.5801,
          "lat": 23.0215
     },
     "list": [
          {
               "main": {
                    "aqi": 2
               },
               "components": {
                    "co": 95.91,
                    "no": 0.17,
                    "no2": 0.79,
                    "o3": 62.61,
                    "so2": 1.36,
                    "pm2_5": 7.8,
                    "pm10": 32.03,
                    "nh3": 0.62
               },
               "dt": 1780035001
          }
     ]
}

In [21]:
print(data['list'][0]["main"]["aqi"])

2

In [22]:
url = f"https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={api_key}&units=metric"

In [23]:
response = requests.get(url)
print(response)

<Response [200]>

In [24]:
data = response.json()
print(data)

{'cod': '200', 'message': 0, 'cnt': 40, 'list': [{'dt': 1780045200, 'main': {'temp': 37.66, 'feels_like': 39.88, 'temp_min': 37.66, 'temp_max': 42.89, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 998, 'humidity': 33, 'temp_kf': -5.23}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02d'}], 'clouds': {'all': 13}, 'wind': {'speed': 7.81, 'deg': 250, 'gust': 8.75}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 09:00:00'}, {'dt': 1780056000, 'main': {'temp': 39.72, 'feels_like': 41.37, 'temp_min': 39.72, 'temp_max': 42.06, 'pressure': 1003, 'sea_level': 1003, 'grnd_level': 996, 'humidity': 27, 'temp_kf': -2.34}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 7}, 'wind': {'speed': 9, 'deg': 282, 'gust': 9.5}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-29 12:00:00'}, {'dt': 1780066800, 'main': {'temp': 34.83, 'feels_like': 36.07, 'temp_min': 34.83, 'temp_max': 34.83, 'pressure': 1003, 'sea_level': 1003, 'grnd_level': 998, 'humidity': 37, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 7.65, 'deg': 276, 'gust': 12.21}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-29 15:00:00'}, {'dt': 1780077600, 'main': {'temp': 31.32, 'feels_like': 34.52, 'temp_min': 31.32, 'temp_max': 31.32, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 999, 'humidity': 56, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 6.01, 'deg': 253, 'gust': 12.05}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-29 18:00:00'}, {'dt': 1780088400, 'main': {'temp': 30.43, 'feels_like': 33.03, 'temp_min': 30.43, 'temp_max': 30.43, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 998, 'humidity': 57, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 6.51, 'deg': 226, 'gust': 9.84}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-29 21:00:00'}, {'dt': 1780099200, 'main': {'temp': 29.17, 'feels_like': 32.17, 'temp_min': 29.17, 'temp_max': 29.17, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 65, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 6.29, 'deg': 210, 'gust': 9.63}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-30 00:00:00'}, {'dt': 1780110000, 'main': {'temp': 31.49, 'feels_like': 34.86, 'temp_min': 31.49, 'temp_max': 31.49, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1001, 'humidity': 56, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 7.82, 'deg': 217, 'gust': 9.92}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 03:00:00'}, {'dt': 1780120800, 'main': {'temp': 38, 'feels_like': 39.45, 'temp_min': 38, 'temp_max': 38, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 30, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 7.65, 'deg': 229, 'gust': 9.18}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 06:00:00'}, {'dt': 1780131600, 'main': {'temp': 42.3, 'feels_like': 43.24, 'temp_min': 42.3, 'temp_max': 42.3, 'pressure': 1002, 'sea_level': 1002, 'grnd_level': 997, 'humidity': 21, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 7.85, 'deg': 238, 'gust': 9.12}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 09:00:00'}, {'dt': 1780142400, 'main': {'temp': 41.89, 'feels_like': 42.58, 'temp_min': 41.89, 'temp_max': 41.89, 'pressure': 1001, 'sea_level': 1001, 'grnd_level': 996, 'humidity': 21, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 7.6, 'deg': 237, 'gust': 8.29}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-30 12:00:00'}, {'dt': 1780153200, 'main': {'temp': 36.28, 'feels_like': 38.34, 'temp_min': 36.28, 'temp_max': 36.28, 'pressure': 1003, 'sea_level': 1003, 'grnd_level': 997, 'humidity': 36, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 5.55, 'deg': 284, 'gust': 9.28}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-30 15:00:00'}, {'dt': 1780164000, 'main': {'temp': 33.55, 'feels_like': 36.23, 'temp_min': 33.55, 'temp_max': 33.55, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 999, 'humidity': 46, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 5.48, 'deg': 241, 'gust': 8.04}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-30 18:00:00'}, {'dt': 1780174800, 'main': {'temp': 30.33, 'feels_like': 33.47, 'temp_min': 30.33, 'temp_max': 30.33, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 60, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 5.48, 'deg': 230, 'gust': 7.74}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-30 21:00:00'}, {'dt': 1780185600, 'main': {'temp': 29.28, 'feels_like': 32.76, 'temp_min': 29.28, 'temp_max': 29.28, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1001, 'humidity': 67, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 31}, 'wind': {'speed': 4.13, 'deg': 210, 'gust': 6.51}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-31 00:00:00'}, {'dt': 1780196400, 'main': {'temp': 31.22, 'feels_like': 35.06, 'temp_min': 31.22, 'temp_max': 31.22, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1003, 'humidity': 59, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 49}, 'wind': {'speed': 5.91, 'deg': 213, 'gust': 6.88}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 03:00:00'}, {'dt': 1780207200, 'main': {'temp': 37.01, 'feels_like': 39.72, 'temp_min': 37.01, 'temp_max': 37.01, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1002, 'humidity': 36, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 30}, 'wind': {'speed': 5.45, 'deg': 231, 'gust': 6.06}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 06:00:00'}, {'dt': 1780218000, 'main': {'temp': 41.22, 'feels_like': 43.18, 'temp_min': 41.22, 'temp_max': 41.22, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 999, 'humidity': 25, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 4.76, 'deg': 242, 'gust': 5.37}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 09:00:00'}, {'dt': 1780228800, 'main': {'temp': 40.8, 'feels_like': 42.87, 'temp_min': 40.8, 'temp_max': 40.8, 'pressure': 1001, 'sea_level': 1001, 'grnd_level': 996, 'humidity': 26, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01d'}], 'clouds': {'all': 0}, 'wind': {'speed': 7.21, 'deg': 241, 'gust': 8.18}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-05-31 12:00:00'}, {'dt': 1780239600, 'main': {'temp': 35.55, 'feels_like': 37.63, 'temp_min': 35.55, 'temp_max': 35.55, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 999, 'humidity': 38, 'temp_kf': 0}, 'weather': [{'id': 801, 'main': 'Clouds', 'description': 'few clouds', 'icon': '02n'}], 'clouds': {'all': 23}, 'wind': {'speed': 2.02, 'deg': 233, 'gust': 3.9}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-31 15:00:00'}, {'dt': 1780250400, 'main': {'temp': 32.57, 'feels_like': 34.67, 'temp_min': 32.57, 'temp_max': 32.57, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1002, 'humidity': 47, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 61}, 'wind': {'speed': 2.98, 'deg': 296, 'gust': 5.25}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-31 18:00:00'}, {'dt': 1780261200, 'main': {'temp': 30.35, 'feels_like': 34.65, 'temp_min': 30.35, 'temp_max': 30.35, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1001, 'humidity': 65, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 99}, 'wind': {'speed': 2.32, 'deg': 268, 'gust': 3.88}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-05-31 21:00:00'}, {'dt': 1780272000, 'main': {'temp': 30.22, 'feels_like': 33.91, 'temp_min': 30.22, 'temp_max': 30.22, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1001, 'humidity': 63, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04n'}], 'clouds': {'all': 100}, 'wind': {'speed': 5.6, 'deg': 223, 'gust': 7}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-01 00:00:00'}, {'dt': 1780282800, 'main': {'temp': 32.15, 'feels_like': 35.41, 'temp_min': 32.15, 'temp_max': 32.15, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1003, 'humidity': 53, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 86}, 'wind': {'speed': 5.58, 'deg': 233, 'gust': 6.73}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 03:00:00'}, {'dt': 1780293600, 'main': {'temp': 37.48, 'feels_like': 39.2, 'temp_min': 37.48, 'temp_max': 37.48, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1002, 'humidity': 32, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 76}, 'wind': {'speed': 5.07, 'deg': 237, 'gust': 5.67}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 06:00:00'}, {'dt': 1780304400, 'main': {'temp': 41.13, 'feels_like': 42.18, 'temp_min': 41.13, 'temp_max': 41.13, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 999, 'humidity': 23, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 57}, 'wind': {'speed': 4.92, 'deg': 241, 'gust': 4.97}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 09:00:00'}, {'dt': 1780315200, 'main': {'temp': 41.27, 'feels_like': 42.41, 'temp_min': 41.27, 'temp_max': 41.27, 'pressure': 1002, 'sea_level': 1002, 'grnd_level': 997, 'humidity': 23, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 39}, 'wind': {'speed': 6.32, 'deg': 248, 'gust': 6.46}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-01 12:00:00'}, {'dt': 1780326000, 'main': {'temp': 34.93, 'feels_like': 38.02, 'temp_min': 34.93, 'temp_max': 34.93, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 43, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 3.65, 'deg': 177, 'gust': 4.13}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-01 15:00:00'}, {'dt': 1780336800, 'main': {'temp': 32.4, 'feels_like': 36.78, 'temp_min': 32.4, 'temp_max': 32.4, 'pressure': 1007, 'sea_level': 1007, 'grnd_level': 1002, 'humidity': 56, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 0}, 'wind': {'speed': 1.2, 'deg': 205, 'gust': 2.37}, 'visibility': 10000, 'pop': 0.2, 'rain': {'3h': 0.12}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-01 18:00:00'}, {'dt': 1780347600, 'main': {'temp': 30.64, 'feels_like': 34.81, 'temp_min': 30.64, 'temp_max': 30.64, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1000, 'humidity': 63, 'temp_kf': 0}, 'weather': [{'id': 800, 'main': 'Clear', 'description': 'clear sky', 'icon': '01n'}], 'clouds': {'all': 0}, 'wind': {'speed': 4.2, 'deg': 280, 'gust': 7.3}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-01 21:00:00'}, {'dt': 1780358400, 'main': {'temp': 30.31, 'feels_like': 34.1, 'temp_min': 30.31, 'temp_max': 30.31, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1001, 'humidity': 63, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03n'}], 'clouds': {'all': 50}, 'wind': {'speed': 4.19, 'deg': 230, 'gust': 5.71}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-02 00:00:00'}, {'dt': 1780369200, 'main': {'temp': 31.58, 'feels_like': 35.3, 'temp_min': 31.58, 'temp_max': 31.58, 'pressure': 1008, 'sea_level': 1008, 'grnd_level': 1003, 'humidity': 57, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 100}, 'wind': {'speed': 3.67, 'deg': 221, 'gust': 4.19}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-02 03:00:00'}, {'dt': 1780380000, 'main': {'temp': 36.7, 'feels_like': 40.2, 'temp_min': 36.7, 'temp_max': 36.7, 'pressure': 1006, 'sea_level': 1006, 'grnd_level': 1001, 'humidity': 39, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 99}, 'wind': {'speed': 4.34, 'deg': 218, 'gust': 4.61}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-02 06:00:00'}, {'dt': 1780390800, 'main': {'temp': 40.37, 'feels_like': 42.53, 'temp_min': 40.37, 'temp_max': 40.37, 'pressure': 1003, 'sea_level': 1003, 'grnd_level': 998, 'humidity': 27, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 96}, 'wind': {'speed': 4.27, 'deg': 240, 'gust': 3.16}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-02 09:00:00'}, {'dt': 1780401600, 'main': {'temp': 39.59, 'feels_like': 41.93, 'temp_min': 39.59, 'temp_max': 39.59, 'pressure': 1001, 'sea_level': 1001, 'grnd_level': 996, 'humidity': 29, 'temp_kf': 0}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'overcast clouds', 'icon': '04d'}], 'clouds': {'all': 98}, 'wind': {'speed': 5.41, 'deg': 205, 'gust': 5.36}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-02 12:00:00'}, {'dt': 1780412400, 'main': {'temp': 33.02, 'feels_like': 37.54, 'temp_min': 33.02, 'temp_max': 33.02, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 998, 'humidity': 54, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 62}, 'wind': {'speed': 6.31, 'deg': 177, 'gust': 9.72}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-02 15:00:00'}, {'dt': 1780423200, 'main': {'temp': 31.09, 'feels_like': 35.04, 'temp_min': 31.09, 'temp_max': 31.09, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 60, 'temp_kf': 0}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'clouds': {'all': 48}, 'wind': {'speed': 5.24, 'deg': 127, 'gust': 7.68}, 'visibility': 10000, 'pop': 0.72, 'rain': {'3h': 1.15}, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-02 18:00:00'}, {'dt': 1780434000, 'main': {'temp': 30.9, 'feels_like': 35.39, 'temp_min': 30.9, 'temp_max': 30.9, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 998, 'humidity': 63, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 76}, 'wind': {'speed': 3.41, 'deg': 226, 'gust': 5.46}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-02 21:00:00'}, {'dt': 1780444800, 'main': {'temp': 30.66, 'feels_like': 35.1, 'temp_min': 30.66, 'temp_max': 30.66, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 999, 'humidity': 64, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04n'}], 'clouds': {'all': 83}, 'wind': {'speed': 2.85, 'deg': 266, 'gust': 5.19}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'n'}, 'dt_txt': '2026-06-03 00:00:00'}, {'dt': 1780455600, 'main': {'temp': 33.05, 'feels_like': 37.29, 'temp_min': 33.05, 'temp_max': 33.05, 'pressure': 1005, 'sea_level': 1005, 'grnd_level': 1000, 'humidity': 53, 'temp_kf': 0}, 'weather': [{'id': 803, 'main': 'Clouds', 'description': 'broken clouds', 'icon': '04d'}], 'clouds': {'all': 65}, 'wind': {'speed': 3.92, 'deg': 224, 'gust': 4.67}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-03 03:00:00'}, {'dt': 1780466400, 'main': {'temp': 38.04, 'feels_like': 41.77, 'temp_min': 38.04, 'temp_max': 38.04, 'pressure': 1004, 'sea_level': 1004, 'grnd_level': 999, 'humidity': 36, 'temp_kf': 0}, 'weather': [{'id': 802, 'main': 'Clouds', 'description': 'scattered clouds', 'icon': '03d'}], 'clouds': {'all': 40}, 'wind': {'speed': 4.33, 'deg': 209, 'gust': 4.23}, 'visibility': 10000, 'pop': 0, 'sys': {'pod': 'd'}, 'dt_txt': '2026-06-03 06:00:00'}], 'city': {'id': 1279233, 'name': 'Ahmedabad', 'coord': {'lat': 23.0215, 'lon': 72.5801}, 'country': 'IN', 'population': 3719710, 'timezone': 19800, 'sunrise': 1780014275, 'sunset': 1780062591}}

In [44]:
print(json.dumps(data, indent=5))

{
     "cod": "200",
     "message": 0,
     "cnt": 40,
     "list": [
          {
               "dt": 1780045200,
               "main": {
                    "temp": 37.66,
                    "feels_like": 39.88,
                    "temp_min": 37.66,
                    "temp_max": 42.89,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 998,
                    "humidity": 33,
                    "temp_kf": -5.23
               },
               "weather": [
                    {
                         "id": 801,
                         "main": "Clouds",
                         "description": "few clouds",
                         "icon": "02d"
                    }
               ],
               "clouds": {
                    "all": 13
               },
               "wind": {
                    "speed": 7.81,
                    "deg": 250,
                    "gust": 8.75
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-29 09:00:00"
          },
          {
               "dt": 1780056000,
               "main": {
                    "temp": 39.72,
                    "feels_like": 41.37,
                    "temp_min": 39.72,
                    "temp_max": 42.06,
                    "pressure": 1003,
                    "sea_level": 1003,
                    "grnd_level": 996,
                    "humidity": 27,
                    "temp_kf": -2.34
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 7
               },
               "wind": {
                    "speed": 9,
                    "deg": 282,
                    "gust": 9.5
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-29 12:00:00"
          },
          {
               "dt": 1780066800,
               "main": {
                    "temp": 34.83,
                    "feels_like": 36.07,
                    "temp_min": 34.83,
                    "temp_max": 34.83,
                    "pressure": 1003,
                    "sea_level": 1003,
                    "grnd_level": 998,
                    "humidity": 37,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 7.65,
                    "deg": 276,
                    "gust": 12.21
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-29 15:00:00"
          },
          {
               "dt": 1780077600,
               "main": {
                    "temp": 31.32,
                    "feels_like": 34.52,
                    "temp_min": 31.32,
                    "temp_max": 31.32,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 999,
                    "humidity": 56,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.01,
                    "deg": 253,
                    "gust": 12.05
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-29 18:00:00"
          },
          {
               "dt": 1780088400,
               "main": {
                    "temp": 30.43,
                    "feels_like": 33.03,
                    "temp_min": 30.43,
                    "temp_max": 30.43,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 998,
                    "humidity": 57,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.51,
                    "deg": 226,
                    "gust": 9.84
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-29 21:00:00"
          },
          {
               "dt": 1780099200,
               "main": {
                    "temp": 29.17,
                    "feels_like": 32.17,
                    "temp_min": 29.17,
                    "temp_max": 29.17,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 65,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.29,
                    "deg": 210,
                    "gust": 9.63
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-30 00:00:00"
          },
          {
               "dt": 1780110000,
               "main": {
                    "temp": 31.49,
                    "feels_like": 34.86,
                    "temp_min": 31.49,
                    "temp_max": 31.49,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1001,
                    "humidity": 56,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 7.82,
                    "deg": 217,
                    "gust": 9.92
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-30 03:00:00"
          },
          {
               "dt": 1780120800,
               "main": {
                    "temp": 38,
                    "feels_like": 39.45,
                    "temp_min": 38,
                    "temp_max": 38,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 30,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 7.65,
                    "deg": 229,
                    "gust": 9.18
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-30 06:00:00"
          },
          {
               "dt": 1780131600,
               "main": {
                    "temp": 42.3,
                    "feels_like": 43.24,
                    "temp_min": 42.3,
                    "temp_max": 42.3,
                    "pressure": 1002,
                    "sea_level": 1002,
                    "grnd_level": 997,
                    "humidity": 21,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 7.85,
                    "deg": 238,
                    "gust": 9.12
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-30 09:00:00"
          },
          {
               "dt": 1780142400,
               "main": {
                    "temp": 41.89,
                    "feels_like": 42.58,
                    "temp_min": 41.89,
                    "temp_max": 41.89,
                    "pressure": 1001,
                    "sea_level": 1001,
                    "grnd_level": 996,
                    "humidity": 21,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 7.6,
                    "deg": 237,
                    "gust": 8.29
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-30 12:00:00"
          },
          {
               "dt": 1780153200,
               "main": {
                    "temp": 36.28,
                    "feels_like": 38.34,
                    "temp_min": 36.28,
                    "temp_max": 36.28,
                    "pressure": 1003,
                    "sea_level": 1003,
                    "grnd_level": 997,
                    "humidity": 36,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.55,
                    "deg": 284,
                    "gust": 9.28
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-30 15:00:00"
          },
          {
               "dt": 1780164000,
               "main": {
                    "temp": 33.55,
                    "feels_like": 36.23,
                    "temp_min": 33.55,
                    "temp_max": 33.55,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 999,
                    "humidity": 46,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.48,
                    "deg": 241,
                    "gust": 8.04
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-30 18:00:00"
          },
          {
               "dt": 1780174800,
               "main": {
                    "temp": 30.33,
                    "feels_like": 33.47,
                    "temp_min": 30.33,
                    "temp_max": 30.33,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 60,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 5.48,
                    "deg": 230,
                    "gust": 7.74
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-30 21:00:00"
          },
          {
               "dt": 1780185600,
               "main": {
                    "temp": 29.28,
                    "feels_like": 32.76,
                    "temp_min": 29.28,
                    "temp_max": 29.28,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1001,
                    "humidity": 67,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 802,
                         "main": "Clouds",
                         "description": "scattered clouds",
                         "icon": "03n"
                    }
               ],
               "clouds": {
                    "all": 31
               },
               "wind": {
                    "speed": 4.13,
                    "deg": 210,
                    "gust": 6.51
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-31 00:00:00"
          },
          {
               "dt": 1780196400,
               "main": {
                    "temp": 31.22,
                    "feels_like": 35.06,
                    "temp_min": 31.22,
                    "temp_max": 31.22,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1003,
                    "humidity": 59,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 802,
                         "main": "Clouds",
                         "description": "scattered clouds",
                         "icon": "03d"
                    }
               ],
               "clouds": {
                    "all": 49
               },
               "wind": {
                    "speed": 5.91,
                    "deg": 213,
                    "gust": 6.88
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-31 03:00:00"
          },
          {
               "dt": 1780207200,
               "main": {
                    "temp": 37.01,
                    "feels_like": 39.72,
                    "temp_min": 37.01,
                    "temp_max": 37.01,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1002,
                    "humidity": 36,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 802,
                         "main": "Clouds",
                         "description": "scattered clouds",
                         "icon": "03d"
                    }
               ],
               "clouds": {
                    "all": 30
               },
               "wind": {
                    "speed": 5.45,
                    "deg": 231,
                    "gust": 6.06
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-31 06:00:00"
          },
          {
               "dt": 1780218000,
               "main": {
                    "temp": 41.22,
                    "feels_like": 43.18,
                    "temp_min": 41.22,
                    "temp_max": 41.22,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 999,
                    "humidity": 25,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.76,
                    "deg": 242,
                    "gust": 5.37
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-31 09:00:00"
          },
          {
               "dt": 1780228800,
               "main": {
                    "temp": 40.8,
                    "feels_like": 42.87,
                    "temp_min": 40.8,
                    "temp_max": 40.8,
                    "pressure": 1001,
                    "sea_level": 1001,
                    "grnd_level": 996,
                    "humidity": 26,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 7.21,
                    "deg": 241,
                    "gust": 8.18
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-31 12:00:00"
          },
          {
               "dt": 1780239600,
               "main": {
                    "temp": 35.55,

In [50]:
date,temp,humidity, windspeed,time,discription = [],[],[],[],[],[]
list1 = data["list"]

In [51]:
for i in list1:
    date.append(i["dt_txt"].split(" ")[0])
    time.append(i["dt_txt"].split(" ")[1])
    temp.append(i["main"]["temp"])
    humidity.append(i["main"]["humidity"])
    windspeed.append(i["wind"]["speed"])
    discription.append(i["weather"][0]["description"])

In [53]:
df = pd.DataFrame({
    'date':date,
    'time':time,
    'temp':temp,
    'humidity':humidity,
    'windspeed':windspeed,
    'discription':discription

})

In [54]:
df

          date      time   temp  humidity  windspeed       discription
0   2026-05-29  09:00:00  37.66        33       7.81        few clouds
1   2026-05-29  12:00:00  39.72        27       9.00         clear sky
2   2026-05-29  15:00:00  34.83        37       7.65         clear sky
3   2026-05-29  18:00:00  31.32        56       6.01         clear sky
4   2026-05-29  21:00:00  30.43        57       6.51         clear sky
5   2026-05-30  00:00:00  29.17        65       6.29         clear sky
6   2026-05-30  03:00:00  31.49        56       7.82         clear sky
7   2026-05-30  06:00:00  38.00        30       7.65         clear sky
8   2026-05-30  09:00:00  42.30        21       7.85         clear sky
9   2026-05-30  12:00:00  41.89        21       7.60         clear sky
10  2026-05-30  15:00:00  36.28        36       5.55         clear sky
11  2026-05-30  18:00:00  33.55        46       5.48         clear sky
12  2026-05-30  21:00:00  30.33        60       5.48         clear sky
13  2026-05-31  00:00:00  29.28        67       4.13  scattered clouds
14  2026-05-31  03:00:00  31.22        59       5.91  scattered clouds
15  2026-05-31  06:00:00  37.01        36       5.45  scattered clouds
16  2026-05-31  09:00:00  41.22        25       4.76         clear sky
17  2026-05-31  12:00:00  40.80        26       7.21         clear sky
18  2026-05-31  15:00:00  35.55        38       2.02        few clouds
19  2026-05-31  18:00:00  32.57        47       2.98     broken clouds
20  2026-05-31  21:00:00  30.35        65       2.32   overcast clouds
21  2026-06-01  00:00:00  30.22        63       5.60   overcast clouds
22  2026-06-01  03:00:00  32.15        53       5.58   overcast clouds
23  2026-06-01  06:00:00  37.48        32       5.07     broken clouds
24  2026-06-01  09:00:00  41.13        23       4.92     broken clouds
25  2026-06-01  12:00:00  41.27        23       6.32  scattered clouds
26  2026-06-01  15:00:00  34.93        43       3.65         clear sky
27  2026-06-01  18:00:00  32.40        56       1.20        light rain
28  2026-06-01  21:00:00  30.64        63       4.20         clear sky
29  2026-06-02  00:00:00  30.31        63       4.19  scattered clouds
30  2026-06-02  03:00:00  31.58        57       3.67   overcast clouds
31  2026-06-02  06:00:00  36.70        39       4.34   overcast clouds
32  2026-06-02  09:00:00  40.37        27       4.27   overcast clouds
33  2026-06-02  12:00:00  39.59        29       5.41   overcast clouds
34  2026-06-02  15:00:00  33.02        54       6.31     broken clouds
35  2026-06-02  18:00:00  31.09        60       5.24        light rain
36  2026-06-02  21:00:00  30.90        63       3.41     broken clouds
37  2026-06-03  00:00:00  30.66        64       2.85     broken clouds
38  2026-06-03  03:00:00  33.05        53       3.92     broken clouds
39  2026-06-03  06:00:00  38.04        36       4.33  scattered clouds

In [56]:
%%writefile local.py
from flask import Flask, jsonify, request

app = Flask(__name__)

# Sample data
faculty = [
    {"id": 1, "name": "Rajesh", "dept": "Mechanical"},
    {"id": 2, "name": "Himanshu", "dept": "ECE"}
]

# ---------- GET ----------
@app.route('/faculty', methods=['GET'])
def get_faculty():
    return jsonify(faculty)


# ---------- POST ----------
@app.route('/faculty', methods=['POST'])
def add_faculty():

    data = request.json

    if "name" not in data or "dept" not in data:
        return jsonify({"message": "Name and Dept required"}), 400

    new_data = {
        "id": len(faculty) + 1,
        "name": data["name"],
        "dept": data["dept"]
    }

    faculty.append(new_data)

    return jsonify(new_data), 201


# ---------- PUT (Full Update) ----------
@app.route('/faculty/<int:id>', methods=['PUT'])
def put_faculty(id):

    data = request.json

    # PUT requires complete object
    if "name" not in data or "dept" not in data:
        return jsonify({"message": "Both name and dept required"}), 400

    for f in faculty:

        if f["id"] == id:

            f["name"] = data["name"]
            f["dept"] = data["dept"]

            return jsonify(f)

    return jsonify({"message": "Not found"}), 404


# ---------- PATCH (Partial Update) ----------
@app.route('/faculty/<int:id>', methods=['PATCH'])
def patch_faculty(id):

    data = request.json

    for f in faculty:

        if f["id"] == id:

            if "name" in data:
                f["name"] = data["name"]

            if "dept" in data:
                f["dept"] = data["dept"]

            return jsonify(f)

    return jsonify({"message": "Not found"}), 404


# ---------- DELETE ----------
@app.route('/faculty/<int:id>', methods=['DELETE'])
def delete_faculty(id):

    global faculty

    for f in faculty:

        if f["id"] == id:

            faculty.remove(f)

            return jsonify({"message": "Deleted successfully"})

    return jsonify({"message": "Not found"}), 404


# ---------- Run Server ----------
if __name__ == '__main__':
    app.run(debug=True,use_reloader=False)

Writing local.py

In [57]:
import requests
import json
url = "http://127.0.0.1:5000/faculty"
response = requests.get(url)
print(response)

<Response [200]>

In [59]:
new_data = {
    "name" : "Dhairya",
    "dept" : "CSE_AI"
}
response = requests.post(url, json=new_data)
print(response)

<Response [201]>

In [60]:
print(response.json())

{'dept': 'CSE_AI', 'id': 4, 'name': 'Dhairya'}

In [62]:
new_data = {'dept': 'CSE_AI', 'name': 'Shrey'}
response = requests.put(url+"/1", json=new_data)
print(response)

<Response [200]>

In [64]:
new_data = {'dept': 'IT'}
response = requests.patch(url+"/4", json=new_data)
print(response)

<Response [200]>

In [66]:
response = requests.delete(url+"/3")
print(response)

<Response [200]>

In [67]:
url = "https://jsonplaceholder.typicode.com/posts"
response = requests.get(url)
print(response)

<Response [200]>

In [73]:
data = response.json()
print(json.dumps(data, indent=4))

[
    {
        "userId": 1,
        "id": 1,
        "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
        "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
    },
    {
        "userId": 1,
        "id": 2,
        "title": "qui est esse",
        "body": "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla"
    },
    {
        "userId": 1,
        "id": 3,
        "title": "ea molestias quasi exercitationem repellat qui ipsa sit aut",
        "body": "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut"
    },
    {
        "userId": 1,
        "id": 4,
        "title": "eum et est occaecati",
        "body": "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit"
    },
    {
        "userId": 1,
        "id": 5,
        "title": "nesciunt quas odio",
        "body": "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque"
    },
    {
        "userId": 1,
        "id": 6,
        "title": "dolorem eum magni eos aperiam quia",
        "body": "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae"
    },
    {
        "userId": 1,
        "id": 7,
        "title": "magnam facilis autem",
        "body": "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas"
    },
    {
        "userId": 1,
        "id": 8,
        "title": "dolorem dolore est ipsam",
        "body": "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae"
    },
    {
        "userId": 1,
        "id": 9,
        "title": "nesciunt iure omnis dolorem tempora et accusantium",
        "body": "consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas"
    },
    {
        "userId": 1,
        "id": 10,
        "title": "optio molestias id quia eum",
        "body": "quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error"
    },
    {
        "userId": 2,
        "id": 11,
        "title": "et ea vero quia laudantium autem",
        "body": "delectus reiciendis molestiae occaecati non minima eveniet qui voluptatibus\naccusamus in eum beatae sit\nvel qui neque voluptates ut commodi qui incidunt\nut animi commodi"
    },
    {
        "userId": 2,
        "id": 12,
        "title": "in quibusdam tempore odit est dolorem",
        "body": "itaque id aut magnam\npraesentium quia et ea odit et ea voluptas et\nsapiente quia nihil amet occaecati quia id voluptatem\nincidunt ea est distinctio odio"
    },
    {
        "userId": 2,
        "id": 13,
        "title": "dolorum ut in voluptas mollitia et saepe quo animi",
        "body": "aut dicta possimus sint mollitia voluptas commodi quo doloremque\niste corrupti reiciendis voluptatem eius rerum\nsit cumque quod eligendi laborum minima\nperferendis recusandae assumenda consectetur porro architecto ipsum ipsam"
    },
    {
        "userId": 2,
        "id": 14,
        "title": "voluptatem eligendi optio",
        "body": "fuga et accusamus dolorum perferendis illo voluptas\nnon doloremque neque facere\nad qui dolorum molestiae beatae\nsed aut voluptas totam sit illum"
    },
    {
        "userId": 2,
        "id": 15,
        "title": "eveniet quod temporibus",
        "body": "reprehenderit quos placeat\nvelit minima officia dolores impedit repudiandae molestiae nam\nvoluptas recusandae quis delectus\nofficiis harum fugiat vitae"
    },
    {
        "userId": 2,
        "id": 16,
        "title": "sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio",
        "body": "suscipit nam nisi quo aperiam aut\nasperiores eos fugit maiores voluptatibus quia\nvoluptatem quis ullam qui in alias quia est\nconsequatur magni mollitia accusamus ea nisi voluptate dicta"
    },
    {
        "userId": 2,
        "id": 17,
        "title": "fugit voluptas sed molestias voluptatem provident",
        "body": "eos voluptas et aut odit natus earum\naspernatur fuga molestiae ullam\ndeserunt ratione qui eos\nqui nihil ratione nemo velit ut aut id quo"
    },
    {
        "userId": 2,
        "id": 18,
        "title": "voluptate et itaque vero tempora molestiae",
        "body": "eveniet quo quis\nlaborum totam consequatur non dolor\nut et est repudiandae\nest voluptatem vel debitis et magnam"
    },
    {
        "userId": 2,
        "id": 19,
        "title": "adipisci placeat illum aut reiciendis qui",
        "body": "illum quis cupiditate provident sit magnam\nea sed aut omnis\nveniam maiores ullam consequatur atque\nadipisci quo iste expedita sit quos voluptas"
    },
    {
        "userId": 2,
        "id": 20,
        "title": "doloribus ad provident suscipit at",
        "body": "qui consequuntur ducimus possimus quisquam amet similique\nsuscipit porro ipsam amet\neos veritatis officiis exercitationem vel fugit aut necessitatibus totam\nomnis rerum consequatur expedita quidem cumque explicabo"
    },
    {
        "userId": 3,
        "id": 21,
        "title": "asperiores ea ipsam voluptatibus modi minima quia sint",
        "body": "repellat aliquid praesentium dolorem quo\nsed totam minus non itaque\nnihil labore molestiae sunt dolor eveniet hic recusandae veniam\ntempora et tenetur expedita sunt"
    },
    {
        "userId": 3,
        "id": 22,
        "title": "dolor sint quo a velit explicabo quia nam",
        "body": "eos qui et ipsum ipsam suscipit aut\nsed omnis non odio\nexpedita earum mollitia molestiae aut atque rem suscipit\nnam impedit esse"
    },
    {
        "userId": 3,
        "id": 23,
        "title": "maxime id vitae nihil numquam",
        "body": "veritatis unde neque eligendi\nquae quod architecto quo neque vitae\nest illo sit tempora doloremque fugit quod\net et vel beatae sequi ullam sed tenetur perspiciatis"
    },
    {
        "userId": 3,
        "id": 24,
        "title": "autem hic labore sunt dolores incidunt",
        "body": "enim et ex nulla\nomnis voluptas quia qui\nvoluptatem consequatur numquam aliquam sunt\ntotam recusandae id dignissimos aut sed asperiores deserunt"
    },
    {
        "userId": 3,
        "id": 25,
        "title": "rem alias distinctio quo quis",
        "body": "ullam consequatur ut\nomnis quis sit vel consequuntur\nipsa eligendi ipsum molestiae et omnis error nostrum\nmolestiae illo tempore quia et distinctio"
    },
    {
        "userId": 3,
        "id": 26,
        "title": "est et quae odit qui non",
        "body": "similique esse doloribus nihil accusamus\nomnis dolorem fuga consequuntur reprehenderit fugit recusandae temporibus\nperspiciatis cum ut laudantium\nomnis aut molestiae vel vero"
    },
    {
        "userId": 3,
        "id": 27,
        "title": "quasi id et eos tenetur aut quo autem",
        "body": "eum sed dolores ipsam sint possimus debitis occaecati\ndebitis qui qui et\nut placeat enim earum aut odit facilis\nconsequatur suscipit necessitatibus rerum sed inventore temporibus consequatur"
    },
    {
        "userId": 3,
        "id": 28,
        "title": "delectus ullam et corporis nulla voluptas sequi",
        "body": "non et quaerat ex quae ad maiores\nmaiores recusandae totam aut blanditiis mollitia quas illo\nut voluptatibus voluptatem\nsimilique nostrum eum"
    },
    {
        "userId": 3,
        "id": 29,
        "title": "iusto eius quod necessitatibus culpa ea",
        "body": "odit magnam ut saepe sed non qui\ntempora atque nihil\naccusamus illum doloribus illo dolor\neligendi repudiandae odit magni similique sed cum maiores"
    },
    {
        "userId": 3,
        "id": 30,
        "title": "a quo magni similique perferendis",
        "body": "alias dolor cumque\nimpedit blanditiis non eveniet odio maxime\nblanditiis amet eius quis tempora quia autem rem\na provident perspiciatis quia"
    },
    {
        "userId": 4,
        "id": 31,
        "title": "ullam ut quidem id aut vel consequuntur",
        "body": "debitis eius sed quibusdam non quis consectetur vitae\nimpedit ut qui consequatur sed aut in\nquidem sit nostrum et maiores adipisci atque\nquaerat voluptatem adipisci repudiandae"
    },
    {
        "userId": 4,
        "id": 32,
        "title": "doloremque illum aliquid sunt",
        "body": "deserunt eos nobis asperiores et hic\nest debitis repellat molestiae optio\nnihil ratione ut eos beatae quibusdam distinctio maiores\nearum voluptates et aut adipisci ea maiores voluptas maxime"
    },
    {
        "userId": 4,
        "id": 33,
        "title": "qui explicabo molestiae dolorem",
        "body": "rerum ut et numquam laborum odit est sit\nid qui sint in\nquasi tenetur tempore aperiam et quaerat qui in\nrerum officiis sequi cumque quod"
    },
    {
        "userId": 4,
        "id": 34,
        "title": "magnam ut rerum iure",
        "body": "ea velit perferendis earum ut voluptatem voluptate itaque iusto\ntotam pariatur in\nnemo voluptatem voluptatem autem magni tempora minima in\nest distinctio qui assumenda accusamus dignissimos officia nesciunt nobis"
    },
    {
        "userId": 4,
        "id": 35,
        "title": "id nihil consequatur molestias animi provident",
        "body": "nisi error delectus possimus ut eligendi vitae\nplaceat eos harum cupiditate facilis reprehenderit voluptatem beatae\nmodi ducimus quo illum voluptas eligendi\net nobis quia fugit"
    },
    {
        "userId": 4,
        "id": 36,
        "title": "fuga nam accusamus voluptas reiciendis itaque",
        "body": "ad mollitia et omnis minus architecto odit\nvoluptas doloremque maxime aut non ipsa qui alias veniam\nblanditiis culpa aut quia nihil cumque facere et occaecati\nqui aspernatur quia eaque ut aperiam inventore"
    },
    {
        "userId": 4,
        "id": 37,
        "title": "provident vel ut sit ratione est",
        "body": "debitis et eaque non officia sed nesciunt pariatur vel\nvoluptatem iste vero et ea\nnumquam aut expedita ipsum nulla in\nvoluptates omnis consequatur aut enim officiis in quam qui"
    },
    {
        "userId": 4,
        "id": 38,
        "title": "explicabo et eos deleniti nostrum ab id repellendus",
        "body": "animi esse sit aut sit nesciunt assumenda eum voluptas\nquia voluptatibus provident quia necessitatibus ea\nrerum repudiandae quia voluptatem delectus fugit aut id quia\nratione optio eos iusto veniam iure"
    },
    {
        "userId": 4,
        "id": 39,
        "title": "eos dolorem iste accusantium est eaque quam",
        "body": "corporis rerum ducimus vel eum accusantium\nmaxime aspernatur a porro possimus iste omnis\nest in deleniti asperiores fuga aut\nvoluptas sapiente vel dolore minus voluptatem incidunt ex"
    },
    {
        "userId": 4,
        "id": 40,
        "title": "enim quo cumque",
        "body": "ut voluptatum aliquid illo tenetur nemo sequi quo facilis\nipsum rem optio mollitia quas\nvoluptatem eum voluptas qui\nunde omnis voluptatem iure quasi maxime voluptas nam"
    },
    {
        "userId": 5,
        "id": 41,
        "title": "non est facere",
        "body": "molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe"
    },
    {
        "userId": 5,
        "id": 42,
        "title": "commodi ullam sint et excepturi error explicabo praesentium voluptas",
        "body": "odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut"
    },
    {
        "userId": 5,
        "id": 43,
        "title": "eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis",
        "body": "similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis"
    },
    {
        "userId": 5,
        "id": 44,
        "title": "optio dolor molestias sit",
        "body": "temporibus est consectetur dolore\net libero debitis vel velit laboriosam quia\nipsum quibusdam qui itaque fuga rem aut\nea et iure quam sed maxime ut distinctio quae"
    },
    {
        "userId": 5,
        "id": 45,
        "title": "ut numquam possimus omnis eius suscipit laudantium iure",
        "body": "est natus reiciendis nihil possimus aut provident\nex et dolor\nrepellat pariatur est\nnobis rerum repellendus dolorem autem"
    },
    {
        "userId": 5,
        "id": 46,
        "title": "aut quo modi neque nostrum ducimus",
        "body": "voluptatem quisquam iste\nvoluptatibus natus officiis facilis dolorem\nquis quas ipsam\nvel et voluptatum in aliquid"
    },
    {
        "userId": 5,
        "id": 47,
        "title": "quibusdam cumque rem aut deserunt",
        "body": "voluptatem assumenda ut qui ut cupiditate aut impedit veniam\noccaecati nemo illum voluptatem laudantium\nmolestiae beatae rerum ea iure soluta nostrum\neligendi et voluptate"
    },
    {
        "userId": 5,
        "id": 48,
        "title": "ut voluptatem illum ea doloribus itaque eos",
        "body": "voluptates quo voluptatem facilis iure occaecati\nvel assumenda rerum officia et\nillum perspiciatis ab deleniti\nlaudantium repellat ad ut et autem reprehenderit"
    },
    {
        "userId": 5,
        "id": 49,
        "title": "laborum non sunt aut ut assumenda perspiciatis voluptas",
        "body": "inventore ab sint\nnatus fugit id nulla sequi architecto nihil quaerat\neos tenetur in in eum veritatis non\nquibusdam officiis aspernatur cumque aut commodi aut"
    },
    {
        "userId": 5,
        "id": 50,
        "title": "repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem",
        "body": "error suscipit maxime adipisci consequuntur recusandae\nvoluptas eligendi et est et voluptates\nquia distinctio ab amet quaerat molestiae et vitae\nadipisci impedit sequi nesciunt quis consectetur"
    },
    {
        "userId": 6,
        "id": 51,
        "title": "soluta aliquam aperiam consequatur illo quis voluptas",
        "body": "sunt dolores aut doloribus\ndolore doloribus voluptates tempora et\ndoloremque et quo\ncum asperiores sit consectetur dolorem"
    },
    {
        "userId": 6,
        "id": 52,
        "title": "qui enim et consequuntur quia animi quis voluptate quibusdam",
        "body": "iusto est quibusdam fuga quas quaerat molestias\na enim ut sit accusamus enim\ntemporibus iusto accusantium provident architecto\nsoluta esse reprehenderit qui laborum"
    },
    {
        "userId": 6,
        "id": 53,
        "title": "ut quo aut ducimus alias",
        "body": "minima harum praesentium eum rerum illo dolore\nquasi exercitationem rerum nam\nporro quis neque quo\nconsequatur minus dolor quidem veritatis sunt non explicabo similique"
    },
    {
        "userId": 6,
        "id": 54,
        "title": "sit asperiores ipsam eveniet odio non quia",
        "body": "totam corporis dignissimos\nvitae dolorem ut occaecati accusamus\nex velit deserunt\net exercitationem vero incidunt corrupti mollitia"
    },
    {
        "userId": 6,
        "id": 55,
        "title": "sit vel voluptatem et non libero",
        "body": "debitis excepturi ea perferendis harum libero optio\neos accusamus cum fuga ut sapiente repudiandae\net ut incidunt omnis molestiae\nnihil ut eum odit"
    },
    {
        "userId": 6,
        "id": 56,
        "title": "qui et at rerum necessitatibus",
        "body": "aut est omnis dolores\nneque rerum quod ea rerum velit pariatur beatae excepturi\net provident voluptas corrupti\ncorporis harum reprehenderit dolores eligendi"
    },
    {
        "userId": 6,
        "id": 57,
        "title": "sed ab est est",
        "body": "at pariatur consequuntur earum quidem\nquo est laudantium soluta voluptatem\nqui ullam et est\net cum voluptas voluptatum repellat est"
    },
    {
        "userId": 6,
        "id": 58,
        "title": "voluptatum itaque dolores nisi et quasi",
        "body": "veniam voluptatum quae adipisci id\net id quia eos ad et dolorem\naliquam quo nisi sunt eos impedit error\nad similique veniam"
    },
    {
        "userId": 6,
        "id": 59,
        "title": "qui commodi dolor at maiores et quis id accusantium",
        "body": "perspiciatis et quam ea autem temporibus non voluptatibus qui\nbeatae a earum officia nesciunt dolores suscipit voluptas et\nanimi doloribus cum rerum quas et magni\net hic ut ut commodi expedita sunt"
    },
    {
        "userId": 6,
        "id": 60,
        "title": "consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere",
        "body": "asperiores sunt ab assumenda cumque modi velit\nqui esse omnis\nvoluptate et fuga perferendis voluptas\nillo ratione amet aut et omnis"
    },
    {
        "userId": 7,
        "id": 61,
        "title": "voluptatem doloribus consectetur est ut ducimus",
        "body": "ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit"
    },
    {
        "userId": 7,
        "id": 62,
        "title": "beatae enim quia vel",
        "body": "enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio"
    },
    {
        "userId": 7,
        "id": 63,
        "title": "voluptas blanditiis repellendus animi ducimus error sapiente et suscipit",
        "body": "enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta"
    },
    {
        "userId": 7,
        "id": 64,
        "title": "et fugit quas eum in in aperiam quod",
        "body": "id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est eos perspiciatis\nincidunt a error provident eaque aut aut qui"
    },
    {
        "userId": 7,
        "id": 65,
        "title": "consequatur id enim sunt et et",
        "body": "voluptatibus ex esse\nsint explicabo est aliquid cumque adipisci fuga repellat labore\nmolestiae corrupti ex saepe at asperiores et perferendis\nnatus id esse incidunt pariatur"
    },
    {
        "userId": 7,
        "id": 66,
        "title": "repudiandae ea animi iusto",
        "body": "officia veritatis tenetur vero qui itaque\nsint non ratione\nsed et ut asperiores iusto eos molestiae nostrum\nveritatis quibusdam et nemo iusto saepe"
    },
    {
        "userId": 7,
        "id": 67,
        "title": "aliquid eos sed fuga est maxime repellendus",
        "body": "reprehenderit id nostrum\nvoluptas doloremque pariatur sint et accusantium quia quod aspernatur\net fugiat amet\nnon sapiente et consequatur necessitatibus molestiae"
    },
    {
        "userId": 7,
        "id": 68,
        "title": "odio quis facere architecto reiciendis optio",

In [72]:
print(response.status_code)

200

In [74]:
print(len(data))

100

In [75]:
params = {"_page":1,"_limit":10}

In [76]:
response = requests.get(url, params=params)
print(response)

<Response [200]>

In [78]:
data = response.json()
print(data)

[{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}, {'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}, {'userId': 1, 'id': 3, 'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}, {'userId': 1, 'id': 4, 'title': 'eum et est occaecati', 'body': 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit'}, {'userId': 1, 'id': 5, 'title': 'nesciunt quas odio', 'body': 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque'}, {'userId': 1, 'id': 6, 'title': 'dolorem eum magni eos aperiam quia', 'body': 'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae'}, {'userId': 1, 'id': 7, 'title': 'magnam facilis autem', 'body': 'dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas'}, {'userId': 1, 'id': 8, 'title': 'dolorem dolore est ipsam', 'body': 'dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae'}, {'userId': 1, 'id': 9, 'title': 'nesciunt iure omnis dolorem tempora et accusantium', 'body': 'consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas'}, {'userId': 1, 'id': 10, 'title': 'optio molestias id quia eum', 'body': 'quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error'}]

In [79]:
print(json.dumps(data, indent=4))

[
    {
        "userId": 1,
        "id": 1,
        "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
        "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
    },
    {
        "userId": 1,
        "id": 2,
        "title": "qui est esse",
        "body": "est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla"
    },
    {
        "userId": 1,
        "id": 3,
        "title": "ea molestias quasi exercitationem repellat qui ipsa sit aut",
        "body": "et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut"
    },
    {
        "userId": 1,
        "id": 4,
        "title": "eum et est occaecati",
        "body": "ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit"
    },
    {
        "userId": 1,
        "id": 5,
        "title": "nesciunt quas odio",
        "body": "repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque"
    },
    {
        "userId": 1,
        "id": 6,
        "title": "dolorem eum magni eos aperiam quia",
        "body": "ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae"
    },
    {
        "userId": 1,
        "id": 7,
        "title": "magnam facilis autem",
        "body": "dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas"
    },
    {
        "userId": 1,
        "id": 8,
        "title": "dolorem dolore est ipsam",
        "body": "dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae"
    },
    {
        "userId": 1,
        "id": 9,
        "title": "nesciunt iure omnis dolorem tempora et accusantium",
        "body": "consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas"
    },
    {
        "userId": 1,
        "id": 10,
        "title": "optio molestias id quia eum",
        "body": "quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error"
    }
]

In [80]:
url = "https://api.github.com/rate_limit"
response = requests.get(url)
print(response)

<Response [200]>

In [81]:
data = response.json()
print(json.dumps(data, indent=4))

{
    "resources": {
        "code_search": {
            "limit": 60,
            "remaining": 57,
            "reset": 1780044559,
            "used": 3,
            "resource": "code_search"
        },
        "core": {
            "limit": 60,
            "remaining": 57,
            "reset": 1780044559,
            "used": 3,
            "resource": "core"
        },
        "graphql": {
            "limit": 0,
            "remaining": 0,
            "reset": 1780044812,
            "used": 0,
            "resource": "graphql"
        },
        "integration_manifest": {
            "limit": 5000,
            "remaining": 5000,
            "reset": 1780044812,
            "used": 0,
            "resource": "integration_manifest"
        },
        "search": {
            "limit": 10,
            "remaining": 10,
            "reset": 1780041272,
            "used": 0,
            "resource": "search"
        }
    },
    "rate": {
        "limit": 60,
        "remaining": 57,
        "reset": 1780044559,
        "used": 3,
        "resource": "core"
    }
}